// Code generated by ent, DO NOT EDIT.

package subscriptionresetcardusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionresetcardusage type in the database.
	Label = "subscription_reset_card_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGrantID holds the string denoting the grant_id field in the database.
	FieldGrantID = "grant_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldPreviousDailyUsageUsd holds the string denoting the previous_daily_usage_usd field in the database.
	FieldPreviousDailyUsageUsd = "previous_daily_usage_usd"
	// FieldPreviousWeeklyUsageUsd holds the string denoting the previous_weekly_usage_usd field in the database.
	FieldPreviousWeeklyUsageUsd = "previous_weekly_usage_usd"
	// FieldPreviousMonthlyUsageUsd holds the string denoting the previous_monthly_usage_usd field in the database.
	FieldPreviousMonthlyUsageUsd = "previous_monthly_usage_usd"
	// FieldPreviousDailyWindowStart holds the string denoting the previous_daily_window_start field in the database.
	FieldPreviousDailyWindowStart = "previous_daily_window_start"
	// FieldPreviousWeeklyWindowStart holds the string denoting the previous_weekly_window_start field in the database.
	FieldPreviousWeeklyWindowStart = "previous_weekly_window_start"
	// FieldPreviousMonthlyWindowStart holds the string denoting the previous_monthly_window_start field in the database.
	FieldPreviousMonthlyWindowStart = "previous_monthly_window_start"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// EdgeGrant holds the string denoting the grant edge name in mutations.
	EdgeGrant = "grant"
	// EdgeSubscription holds the string denoting the subscription edge name in mutations.
	EdgeSubscription = "subscription"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the subscriptionresetcardusage in the database.
	Table = "subscription_reset_card_usages"
	// GrantTable is the table that holds the grant relation/edge.
	GrantTable = "subscription_reset_card_usages"
	// GrantInverseTable is the table name for the SubscriptionResetCardGrant entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionresetcardgrant" package.
	GrantInverseTable = "subscription_reset_card_grants"
	// GrantColumn is the table column denoting the grant relation/edge.
	GrantColumn = "grant_id"
	// SubscriptionTable is the table that holds the subscription relation/edge.
	SubscriptionTable = "subscription_reset_card_usages"
	// SubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	SubscriptionInverseTable = "user_subscriptions"
	// SubscriptionColumn is the table column denoting the subscription relation/edge.
	SubscriptionColumn = "subscription_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "subscription_reset_card_usages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "subscription_reset_card_usages"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for subscriptionresetcardusage fields.
var Columns = []string{
	FieldID,
	FieldGrantID,
	FieldSubscriptionID,
	FieldUserID,
	FieldGroupID,
	FieldMode,
	FieldRequestID,
	FieldPreviousDailyUsageUsd,
	FieldPreviousWeeklyUsageUsd,
	FieldPreviousMonthlyUsageUsd,
	FieldPreviousDailyWindowStart,
	FieldPreviousWeeklyWindowStart,
	FieldPreviousMonthlyWindowStart,
	FieldUsedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultPreviousDailyUsageUsd holds the default value on creation for the "previous_daily_usage_usd" field.
	DefaultPreviousDailyUsageUsd float64
	// DefaultPreviousWeeklyUsageUsd holds the default value on creation for the "previous_weekly_usage_usd" field.
	DefaultPreviousWeeklyUsageUsd float64
	// DefaultPreviousMonthlyUsageUsd holds the default value on creation for the "previous_monthly_usage_usd" field.
	DefaultPreviousMonthlyUsageUsd float64
	// DefaultUsedAt holds the default value on creation for the "used_at" field.
	DefaultUsedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionResetCardUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGrantID orders the results by the grant_id field.
func ByGrantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByPreviousDailyUsageUsd orders the results by the previous_daily_usage_usd field.
func ByPreviousDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousDailyUsageUsd, opts...).ToFunc()
}

// ByPreviousWeeklyUsageUsd orders the results by the previous_weekly_usage_usd field.
func ByPreviousWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousWeeklyUsageUsd, opts...).ToFunc()
}

// ByPreviousMonthlyUsageUsd orders the results by the previous_monthly_usage_usd field.
func ByPreviousMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousMonthlyUsageUsd, opts...).ToFunc()
}

// ByPreviousDailyWindowStart orders the results by the previous_daily_window_start field.
func ByPreviousDailyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousDailyWindowStart, opts...).ToFunc()
}

// ByPreviousWeeklyWindowStart orders the results by the previous_weekly_window_start field.
func ByPreviousWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousWeeklyWindowStart, opts...).ToFunc()
}

// ByPreviousMonthlyWindowStart orders the results by the previous_monthly_window_start field.
func ByPreviousMonthlyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousMonthlyWindowStart, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByGrantField orders the results by grant field.
func ByGrantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantStep(), sql.OrderByField(field, opts...))
	}
}

// BySubscriptionField orders the results by subscription field.
func BySubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGrantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GrantTable, GrantColumn),
	)
}
func newSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
