// Code generated by ent, DO NOT EDIT.

package subscriptionresetcardusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldID, id))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldGrantID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldSubscriptionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldGroupID, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldMode, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldRequestID, v))
}

// PreviousDailyUsageUsd applies equality check predicate on the "previous_daily_usage_usd" field. It's identical to PreviousDailyUsageUsdEQ.
func PreviousDailyUsageUsd(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousDailyUsageUsd, v))
}

// PreviousWeeklyUsageUsd applies equality check predicate on the "previous_weekly_usage_usd" field. It's identical to PreviousWeeklyUsageUsdEQ.
func PreviousWeeklyUsageUsd(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousMonthlyUsageUsd applies equality check predicate on the "previous_monthly_usage_usd" field. It's identical to PreviousMonthlyUsageUsdEQ.
func PreviousMonthlyUsageUsd(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousDailyWindowStart applies equality check predicate on the "previous_daily_window_start" field. It's identical to PreviousDailyWindowStartEQ.
func PreviousDailyWindowStart(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousDailyWindowStart, v))
}

// PreviousWeeklyWindowStart applies equality check predicate on the "previous_weekly_window_start" field. It's identical to PreviousWeeklyWindowStartEQ.
func PreviousWeeklyWindowStart(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousWeeklyWindowStart, v))
}

// PreviousMonthlyWindowStart applies equality check predicate on the "previous_monthly_window_start" field. It's identical to PreviousMonthlyWindowStartEQ.
func PreviousMonthlyWindowStart(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousMonthlyWindowStart, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldUsedAt, v))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldGrantID, vs...))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldGroupID, vs...))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldContainsFold(FieldMode, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldContainsFold(FieldRequestID, v))
}

// PreviousDailyUsageUsdEQ applies the EQ predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousDailyUsageUsd, v))
}

// PreviousDailyUsageUsdNEQ applies the NEQ predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdNEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousDailyUsageUsd, v))
}

// PreviousDailyUsageUsdIn applies the In predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousDailyUsageUsd, vs...))
}

// PreviousDailyUsageUsdNotIn applies the NotIn predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdNotIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousDailyUsageUsd, vs...))
}

// PreviousDailyUsageUsdGT applies the GT predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdGT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousDailyUsageUsd, v))
}

// PreviousDailyUsageUsdGTE applies the GTE predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdGTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousDailyUsageUsd, v))
}

// PreviousDailyUsageUsdLT applies the LT predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdLT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousDailyUsageUsd, v))
}

// PreviousDailyUsageUsdLTE applies the LTE predicate on the "previous_daily_usage_usd" field.
func PreviousDailyUsageUsdLTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousDailyUsageUsd, v))
}

// PreviousWeeklyUsageUsdEQ applies the EQ predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousWeeklyUsageUsdNEQ applies the NEQ predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdNEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousWeeklyUsageUsdIn applies the In predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousWeeklyUsageUsd, vs...))
}

// PreviousWeeklyUsageUsdNotIn applies the NotIn predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdNotIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousWeeklyUsageUsd, vs...))
}

// PreviousWeeklyUsageUsdGT applies the GT predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdGT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousWeeklyUsageUsdGTE applies the GTE predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdGTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousWeeklyUsageUsdLT applies the LT predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdLT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousWeeklyUsageUsdLTE applies the LTE predicate on the "previous_weekly_usage_usd" field.
func PreviousWeeklyUsageUsdLTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousWeeklyUsageUsd, v))
}

// PreviousMonthlyUsageUsdEQ applies the EQ predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousMonthlyUsageUsdNEQ applies the NEQ predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdNEQ(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousMonthlyUsageUsdIn applies the In predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousMonthlyUsageUsd, vs...))
}

// PreviousMonthlyUsageUsdNotIn applies the NotIn predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdNotIn(vs ...float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousMonthlyUsageUsd, vs...))
}

// PreviousMonthlyUsageUsdGT applies the GT predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdGT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousMonthlyUsageUsdGTE applies the GTE predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdGTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousMonthlyUsageUsdLT applies the LT predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdLT(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousMonthlyUsageUsdLTE applies the LTE predicate on the "previous_monthly_usage_usd" field.
func PreviousMonthlyUsageUsdLTE(v float64) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousMonthlyUsageUsd, v))
}

// PreviousDailyWindowStartEQ applies the EQ predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartNEQ applies the NEQ predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartNEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartIn applies the In predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousDailyWindowStart, vs...))
}

// PreviousDailyWindowStartNotIn applies the NotIn predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousDailyWindowStart, vs...))
}

// PreviousDailyWindowStartGT applies the GT predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartGT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartGTE applies the GTE predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartGTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartLT applies the LT predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartLT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartLTE applies the LTE predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartLTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousDailyWindowStart, v))
}

// PreviousDailyWindowStartIsNil applies the IsNil predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartIsNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIsNull(FieldPreviousDailyWindowStart))
}

// PreviousDailyWindowStartNotNil applies the NotNil predicate on the "previous_daily_window_start" field.
func PreviousDailyWindowStartNotNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotNull(FieldPreviousDailyWindowStart))
}

// PreviousWeeklyWindowStartEQ applies the EQ predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartNEQ applies the NEQ predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartNEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartIn applies the In predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousWeeklyWindowStart, vs...))
}

// PreviousWeeklyWindowStartNotIn applies the NotIn predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousWeeklyWindowStart, vs...))
}

// PreviousWeeklyWindowStartGT applies the GT predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartGT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartGTE applies the GTE predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartGTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartLT applies the LT predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartLT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartLTE applies the LTE predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartLTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousWeeklyWindowStart, v))
}

// PreviousWeeklyWindowStartIsNil applies the IsNil predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartIsNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIsNull(FieldPreviousWeeklyWindowStart))
}

// PreviousWeeklyWindowStartNotNil applies the NotNil predicate on the "previous_weekly_window_start" field.
func PreviousWeeklyWindowStartNotNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotNull(FieldPreviousWeeklyWindowStart))
}

// PreviousMonthlyWindowStartEQ applies the EQ predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartNEQ applies the NEQ predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartNEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartIn applies the In predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldPreviousMonthlyWindowStart, vs...))
}

// PreviousMonthlyWindowStartNotIn applies the NotIn predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldPreviousMonthlyWindowStart, vs...))
}

// PreviousMonthlyWindowStartGT applies the GT predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartGT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartGTE applies the GTE predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartGTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartLT applies the LT predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartLT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartLTE applies the LTE predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartLTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldPreviousMonthlyWindowStart, v))
}

// PreviousMonthlyWindowStartIsNil applies the IsNil predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartIsNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIsNull(FieldPreviousMonthlyWindowStart))
}

// PreviousMonthlyWindowStartNotNil applies the NotNil predicate on the "previous_monthly_window_start" field.
func PreviousMonthlyWindowStartNotNil() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotNull(FieldPreviousMonthlyWindowStart))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.FieldLTE(FieldUsedAt, v))
}

// HasGrant applies the HasEdge predicate on the "grant" edge.
func HasGrant() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GrantTable, GrantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantWith applies the HasEdge predicate on the "grant" edge with a given conditions (other predicates).
func HasGrantWith(preds ...predicate.SubscriptionResetCardGrant) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := newGrantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionResetCardUsage) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionResetCardUsage) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionResetCardUsage) predicate.SubscriptionResetCardUsage {
	return predicate.SubscriptionResetCardUsage(sql.NotPredicates(p))
}
