// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardUsageUpdate is the builder for updating SubscriptionResetCardUsage entities.
type SubscriptionResetCardUsageUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionResetCardUsageMutation
}

// Where appends a list predicates to the SubscriptionResetCardUsageUpdate builder.
func (_u *SubscriptionResetCardUsageUpdate) Where(ps ...predicate.SubscriptionResetCardUsage) *SubscriptionResetCardUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *SubscriptionResetCardUsageUpdate) SetGrantID(v int64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableGrantID(v *int64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionResetCardUsageUpdate) SetSubscriptionID(v int64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardUsageUpdate) SetUserID(v int64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableUserID(v *int64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetCardUsageUpdate) SetGroupID(v int64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableGroupID(v *int64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *SubscriptionResetCardUsageUpdate) SetMode(v string) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableMode(v *string) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionResetCardUsageUpdate) SetRequestID(v string) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillableRequestID(v *string) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *SubscriptionResetCardUsageUpdate) ClearRequestID() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.ResetPreviousDailyUsageUsd()
	_u.mutation.SetPreviousDailyUsageUsd(v)
	return _u
}

// SetNillablePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousDailyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousDailyUsageUsd(*v)
	}
	return _u
}

// AddPreviousDailyUsageUsd adds value to the "previous_daily_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) AddPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.AddPreviousDailyUsageUsd(v)
	return _u
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.ResetPreviousWeeklyUsageUsd()
	_u.mutation.SetPreviousWeeklyUsageUsd(v)
	return _u
}

// SetNillablePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousWeeklyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousWeeklyUsageUsd(*v)
	}
	return _u
}

// AddPreviousWeeklyUsageUsd adds value to the "previous_weekly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) AddPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.AddPreviousWeeklyUsageUsd(v)
	return _u
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.ResetPreviousMonthlyUsageUsd()
	_u.mutation.SetPreviousMonthlyUsageUsd(v)
	return _u
}

// SetNillablePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousMonthlyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousMonthlyUsageUsd(*v)
	}
	return _u
}

// AddPreviousMonthlyUsageUsd adds value to the "previous_monthly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdate) AddPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpdate {
	_u.mutation.AddPreviousMonthlyUsageUsd(v)
	return _u
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetPreviousDailyWindowStart(v)
	return _u
}

// SetNillablePreviousDailyWindowStart sets the "previous_daily_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousDailyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousDailyWindowStart(*v)
	}
	return _u
}

// ClearPreviousDailyWindowStart clears the value of the "previous_daily_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) ClearPreviousDailyWindowStart() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearPreviousDailyWindowStart()
	return _u
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetPreviousWeeklyWindowStart(v)
	return _u
}

// SetNillablePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousWeeklyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousWeeklyWindowStart(*v)
	}
	return _u
}

// ClearPreviousWeeklyWindowStart clears the value of the "previous_weekly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) ClearPreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearPreviousWeeklyWindowStart()
	return _u
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdate {
	_u.mutation.SetPreviousMonthlyWindowStart(v)
	return _u
}

// SetNillablePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdate) SetNillablePreviousMonthlyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdate {
	if v != nil {
		_u.SetPreviousMonthlyWindowStart(*v)
	}
	return _u
}

// ClearPreviousMonthlyWindowStart clears the value of the "previous_monthly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdate) ClearPreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearPreviousMonthlyWindowStart()
	return _u
}

// SetGrant sets the "grant" edge to the SubscriptionResetCardGrant entity.
func (_u *SubscriptionResetCardUsageUpdate) SetGrant(v *SubscriptionResetCardGrant) *SubscriptionResetCardUsageUpdate {
	return _u.SetGrantID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUsageUpdate) SetSubscription(v *UserSubscription) *SubscriptionResetCardUsageUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardUsageUpdate) SetUser(v *User) *SubscriptionResetCardUsageUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetCardUsageUpdate) SetGroup(v *Group) *SubscriptionResetCardUsageUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetCardUsageMutation object of the builder.
func (_u *SubscriptionResetCardUsageUpdate) Mutation() *SubscriptionResetCardUsageMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the SubscriptionResetCardGrant entity.
func (_u *SubscriptionResetCardUsageUpdate) ClearGrant() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearGrant()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUsageUpdate) ClearSubscription() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardUsageUpdate) ClearUser() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetCardUsageUpdate) ClearGroup() *SubscriptionResetCardUsageUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionResetCardUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionResetCardUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardUsageUpdate) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := subscriptionresetcardusage.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionresetcardusage.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.request_id": %w`, err)}
		}
	}
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.grant"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.subscription"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.group"`)
	}
	return nil
}

func (_u *SubscriptionResetCardUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcardusage.Table, subscriptionresetcardusage.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.PreviousDailyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousDailyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousWeeklyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousWeeklyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousMonthlyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousMonthlyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousDailyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousDailyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousWeeklyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousWeeklyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousMonthlyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousMonthlyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, field.TypeTime)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GrantTable,
			Columns: []string{subscriptionresetcardusage.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GrantTable,
			Columns: []string{subscriptionresetcardusage.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.SubscriptionTable,
			Columns: []string{subscriptionresetcardusage.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.SubscriptionTable,
			Columns: []string{subscriptionresetcardusage.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.UserTable,
			Columns: []string{subscriptionresetcardusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.UserTable,
			Columns: []string{subscriptionresetcardusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GroupTable,
			Columns: []string{subscriptionresetcardusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GroupTable,
			Columns: []string{subscriptionresetcardusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcardusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionResetCardUsageUpdateOne is the builder for updating a single SubscriptionResetCardUsage entity.
type SubscriptionResetCardUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionResetCardUsageMutation
}

// SetGrantID sets the "grant_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetGrantID(v int64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableGrantID(v *int64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetSubscriptionID(v int64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetUserID(v int64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableUserID(v *int64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetGroupID(v int64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableGroupID(v *int64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetMode(v string) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableMode(v *string) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetRequestID(v string) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillableRequestID(v *string) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearRequestID() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ResetPreviousDailyUsageUsd()
	_u.mutation.SetPreviousDailyUsageUsd(v)
	return _u
}

// SetNillablePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousDailyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousDailyUsageUsd(*v)
	}
	return _u
}

// AddPreviousDailyUsageUsd adds value to the "previous_daily_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) AddPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.AddPreviousDailyUsageUsd(v)
	return _u
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ResetPreviousWeeklyUsageUsd()
	_u.mutation.SetPreviousWeeklyUsageUsd(v)
	return _u
}

// SetNillablePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousWeeklyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousWeeklyUsageUsd(*v)
	}
	return _u
}

// AddPreviousWeeklyUsageUsd adds value to the "previous_weekly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) AddPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.AddPreviousWeeklyUsageUsd(v)
	return _u
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ResetPreviousMonthlyUsageUsd()
	_u.mutation.SetPreviousMonthlyUsageUsd(v)
	return _u
}

// SetNillablePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousMonthlyUsageUsd(v *float64) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousMonthlyUsageUsd(*v)
	}
	return _u
}

// AddPreviousMonthlyUsageUsd adds value to the "previous_monthly_usage_usd" field.
func (_u *SubscriptionResetCardUsageUpdateOne) AddPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.AddPreviousMonthlyUsageUsd(v)
	return _u
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetPreviousDailyWindowStart(v)
	return _u
}

// SetNillablePreviousDailyWindowStart sets the "previous_daily_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousDailyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousDailyWindowStart(*v)
	}
	return _u
}

// ClearPreviousDailyWindowStart clears the value of the "previous_daily_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearPreviousDailyWindowStart() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearPreviousDailyWindowStart()
	return _u
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetPreviousWeeklyWindowStart(v)
	return _u
}

// SetNillablePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousWeeklyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousWeeklyWindowStart(*v)
	}
	return _u
}

// ClearPreviousWeeklyWindowStart clears the value of the "previous_weekly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearPreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearPreviousWeeklyWindowStart()
	return _u
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.SetPreviousMonthlyWindowStart(v)
	return _u
}

// SetNillablePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field if the given value is not nil.
func (_u *SubscriptionResetCardUsageUpdateOne) SetNillablePreviousMonthlyWindowStart(v *time.Time) *SubscriptionResetCardUsageUpdateOne {
	if v != nil {
		_u.SetPreviousMonthlyWindowStart(*v)
	}
	return _u
}

// ClearPreviousMonthlyWindowStart clears the value of the "previous_monthly_window_start" field.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearPreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearPreviousMonthlyWindowStart()
	return _u
}

// SetGrant sets the "grant" edge to the SubscriptionResetCardGrant entity.
func (_u *SubscriptionResetCardUsageUpdateOne) SetGrant(v *SubscriptionResetCardGrant) *SubscriptionResetCardUsageUpdateOne {
	return _u.SetGrantID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUsageUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionResetCardUsageUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardUsageUpdateOne) SetUser(v *User) *SubscriptionResetCardUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetCardUsageUpdateOne) SetGroup(v *Group) *SubscriptionResetCardUsageUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetCardUsageMutation object of the builder.
func (_u *SubscriptionResetCardUsageUpdateOne) Mutation() *SubscriptionResetCardUsageMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the SubscriptionResetCardGrant entity.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearGrant() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearGrant()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearSubscription() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearUser() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetCardUsageUpdateOne) ClearGroup() *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the SubscriptionResetCardUsageUpdate builder.
func (_u *SubscriptionResetCardUsageUpdateOne) Where(ps ...predicate.SubscriptionResetCardUsage) *SubscriptionResetCardUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionResetCardUsageUpdateOne) Select(field string, fields ...string) *SubscriptionResetCardUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionResetCardUsage entity.
func (_u *SubscriptionResetCardUsageUpdateOne) Save(ctx context.Context) (*SubscriptionResetCardUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardUsageUpdateOne) SaveX(ctx context.Context) *SubscriptionResetCardUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionResetCardUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardUsageUpdateOne) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := subscriptionresetcardusage.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionresetcardusage.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.request_id": %w`, err)}
		}
	}
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.grant"`)
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.subscription"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardUsage.group"`)
	}
	return nil
}

func (_u *SubscriptionResetCardUsageUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionResetCardUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcardusage.Table, subscriptionresetcardusage.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionResetCardUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcardusage.FieldID)
		for _, f := range fields {
			if !subscriptionresetcardusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionresetcardusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.PreviousDailyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousDailyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousWeeklyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousWeeklyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousMonthlyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousMonthlyUsageUsd(); ok {
		_spec.AddField(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PreviousDailyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousDailyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousWeeklyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousWeeklyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousMonthlyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousMonthlyWindowStartCleared() {
		_spec.ClearField(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, field.TypeTime)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GrantTable,
			Columns: []string{subscriptionresetcardusage.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GrantTable,
			Columns: []string{subscriptionresetcardusage.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.SubscriptionTable,
			Columns: []string{subscriptionresetcardusage.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.SubscriptionTable,
			Columns: []string{subscriptionresetcardusage.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.UserTable,
			Columns: []string{subscriptionresetcardusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.UserTable,
			Columns: []string{subscriptionresetcardusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GroupTable,
			Columns: []string{subscriptionresetcardusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GroupTable,
			Columns: []string{subscriptionresetcardusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionResetCardUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcardusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
