// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetpreference"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetPreferenceUpdate is the builder for updating SubscriptionResetPreference entities.
type SubscriptionResetPreferenceUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionResetPreferenceMutation
}

// Where appends a list predicates to the SubscriptionResetPreferenceUpdate builder.
func (_u *SubscriptionResetPreferenceUpdate) Where(ps ...predicate.SubscriptionResetPreference) *SubscriptionResetPreferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetPreferenceUpdate) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetPreferenceUpdate) SetUserID(v int64) *SubscriptionResetPreferenceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdate) SetNillableUserID(v *int64) *SubscriptionResetPreferenceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetPreferenceUpdate) SetGroupID(v int64) *SubscriptionResetPreferenceUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdate) SetNillableGroupID(v *int64) *SubscriptionResetPreferenceUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (_u *SubscriptionResetPreferenceUpdate) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceUpdate {
	_u.mutation.SetAutoUseEnabled(v)
	return _u
}

// SetNillableAutoUseEnabled sets the "auto_use_enabled" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdate) SetNillableAutoUseEnabled(v *bool) *SubscriptionResetPreferenceUpdate {
	if v != nil {
		_u.SetAutoUseEnabled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetPreferenceUpdate) SetUser(v *User) *SubscriptionResetPreferenceUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetPreferenceUpdate) SetGroup(v *Group) *SubscriptionResetPreferenceUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetPreferenceMutation object of the builder.
func (_u *SubscriptionResetPreferenceUpdate) Mutation() *SubscriptionResetPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetPreferenceUpdate) ClearUser() *SubscriptionResetPreferenceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetPreferenceUpdate) ClearGroup() *SubscriptionResetPreferenceUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionResetPreferenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetPreferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionResetPreferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetPreferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetPreferenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionresetpreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetPreferenceUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetPreference.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetPreference.group"`)
	}
	return nil
}

func (_u *SubscriptionResetPreferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetpreference.Table, subscriptionresetpreference.Columns, sqlgraph.NewFieldSpec(subscriptionresetpreference.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AutoUseEnabled(); ok {
		_spec.SetField(subscriptionresetpreference.FieldAutoUseEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.UserTable,
			Columns: []string{subscriptionresetpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.UserTable,
			Columns: []string{subscriptionresetpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.GroupTable,
			Columns: []string{subscriptionresetpreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.GroupTable,
			Columns: []string{subscriptionresetpreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionResetPreferenceUpdateOne is the builder for updating a single SubscriptionResetPreference entity.
type SubscriptionResetPreferenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionResetPreferenceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetPreferenceUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetPreferenceUpdateOne) SetUserID(v int64) *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdateOne) SetNillableUserID(v *int64) *SubscriptionResetPreferenceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetPreferenceUpdateOne) SetGroupID(v int64) *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdateOne) SetNillableGroupID(v *int64) *SubscriptionResetPreferenceUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (_u *SubscriptionResetPreferenceUpdateOne) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.SetAutoUseEnabled(v)
	return _u
}

// SetNillableAutoUseEnabled sets the "auto_use_enabled" field if the given value is not nil.
func (_u *SubscriptionResetPreferenceUpdateOne) SetNillableAutoUseEnabled(v *bool) *SubscriptionResetPreferenceUpdateOne {
	if v != nil {
		_u.SetAutoUseEnabled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetPreferenceUpdateOne) SetUser(v *User) *SubscriptionResetPreferenceUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetPreferenceUpdateOne) SetGroup(v *Group) *SubscriptionResetPreferenceUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetPreferenceMutation object of the builder.
func (_u *SubscriptionResetPreferenceUpdateOne) Mutation() *SubscriptionResetPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetPreferenceUpdateOne) ClearUser() *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetPreferenceUpdateOne) ClearGroup() *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the SubscriptionResetPreferenceUpdate builder.
func (_u *SubscriptionResetPreferenceUpdateOne) Where(ps ...predicate.SubscriptionResetPreference) *SubscriptionResetPreferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionResetPreferenceUpdateOne) Select(field string, fields ...string) *SubscriptionResetPreferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionResetPreference entity.
func (_u *SubscriptionResetPreferenceUpdateOne) Save(ctx context.Context) (*SubscriptionResetPreference, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetPreferenceUpdateOne) SaveX(ctx context.Context) *SubscriptionResetPreference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionResetPreferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetPreferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetPreferenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionresetpreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetPreferenceUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetPreference.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetPreference.group"`)
	}
	return nil
}

func (_u *SubscriptionResetPreferenceUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionResetPreference, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetpreference.Table, subscriptionresetpreference.Columns, sqlgraph.NewFieldSpec(subscriptionresetpreference.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionResetPreference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetpreference.FieldID)
		for _, f := range fields {
			if !subscriptionresetpreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionresetpreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AutoUseEnabled(); ok {
		_spec.SetField(subscriptionresetpreference.FieldAutoUseEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.UserTable,
			Columns: []string{subscriptionresetpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.UserTable,
			Columns: []string{subscriptionresetpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.GroupTable,
			Columns: []string{subscriptionresetpreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.GroupTable,
			Columns: []string{subscriptionresetpreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionResetPreference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
