// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardUsageQuery is the builder for querying SubscriptionResetCardUsage entities.
type SubscriptionResetCardUsageQuery struct {
	config
	ctx              *QueryContext
	order            []subscriptionresetcardusage.OrderOption
	inters           []Interceptor
	predicates       []predicate.SubscriptionResetCardUsage
	withGrant        *SubscriptionResetCardGrantQuery
	withSubscription *UserSubscriptionQuery
	withUser         *UserQuery
	withGroup        *GroupQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionResetCardUsageQuery builder.
func (_q *SubscriptionResetCardUsageQuery) Where(ps ...predicate.SubscriptionResetCardUsage) *SubscriptionResetCardUsageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionResetCardUsageQuery) Limit(limit int) *SubscriptionResetCardUsageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionResetCardUsageQuery) Offset(offset int) *SubscriptionResetCardUsageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionResetCardUsageQuery) Unique(unique bool) *SubscriptionResetCardUsageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionResetCardUsageQuery) Order(o ...subscriptionresetcardusage.OrderOption) *SubscriptionResetCardUsageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGrant chains the current query on the "grant" edge.
func (_q *SubscriptionResetCardUsageQuery) QueryGrant() *SubscriptionResetCardGrantQuery {
	query := (&SubscriptionResetCardGrantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardusage.Table, subscriptionresetcardusage.FieldID, selector),
			sqlgraph.To(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardusage.GrantTable, subscriptionresetcardusage.GrantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscription chains the current query on the "subscription" edge.
func (_q *SubscriptionResetCardUsageQuery) QuerySubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardusage.Table, subscriptionresetcardusage.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardusage.SubscriptionTable, subscriptionresetcardusage.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *SubscriptionResetCardUsageQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardusage.Table, subscriptionresetcardusage.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardusage.UserTable, subscriptionresetcardusage.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *SubscriptionResetCardUsageQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardusage.Table, subscriptionresetcardusage.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardusage.GroupTable, subscriptionresetcardusage.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionResetCardUsage entity from the query.
// Returns a *NotFoundError when no SubscriptionResetCardUsage was found.
func (_q *SubscriptionResetCardUsageQuery) First(ctx context.Context) (*SubscriptionResetCardUsage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionresetcardusage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) FirstX(ctx context.Context) *SubscriptionResetCardUsage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionResetCardUsage ID from the query.
// Returns a *NotFoundError when no SubscriptionResetCardUsage ID was found.
func (_q *SubscriptionResetCardUsageQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionresetcardusage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionResetCardUsage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionResetCardUsage entity is found.
// Returns a *NotFoundError when no SubscriptionResetCardUsage entities are found.
func (_q *SubscriptionResetCardUsageQuery) Only(ctx context.Context) (*SubscriptionResetCardUsage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionresetcardusage.Label}
	default:
		return nil, &NotSingularError{subscriptionresetcardusage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) OnlyX(ctx context.Context) *SubscriptionResetCardUsage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionResetCardUsage ID in the query.
// Returns a *NotSingularError when more than one SubscriptionResetCardUsage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionResetCardUsageQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionresetcardusage.Label}
	default:
		err = &NotSingularError{subscriptionresetcardusage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionResetCardUsages.
func (_q *SubscriptionResetCardUsageQuery) All(ctx context.Context) ([]*SubscriptionResetCardUsage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionResetCardUsage, *SubscriptionResetCardUsageQuery]()
	return withInterceptors[[]*SubscriptionResetCardUsage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) AllX(ctx context.Context) []*SubscriptionResetCardUsage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionResetCardUsage IDs.
func (_q *SubscriptionResetCardUsageQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionresetcardusage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionResetCardUsageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionResetCardUsageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionResetCardUsageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionResetCardUsageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionResetCardUsageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionResetCardUsageQuery) Clone() *SubscriptionResetCardUsageQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionResetCardUsageQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]subscriptionresetcardusage.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.SubscriptionResetCardUsage{}, _q.predicates...),
		withGrant:        _q.withGrant.Clone(),
		withSubscription: _q.withSubscription.Clone(),
		withUser:         _q.withUser.Clone(),
		withGroup:        _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGrant tells the query-builder to eager-load the nodes that are connected to
// the "grant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardUsageQuery) WithGrant(opts ...func(*SubscriptionResetCardGrantQuery)) *SubscriptionResetCardUsageQuery {
	query := (&SubscriptionResetCardGrantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrant = query
	return _q
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardUsageQuery) WithSubscription(opts ...func(*UserSubscriptionQuery)) *SubscriptionResetCardUsageQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscription = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardUsageQuery) WithUser(opts ...func(*UserQuery)) *SubscriptionResetCardUsageQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardUsageQuery) WithGroup(opts ...func(*GroupQuery)) *SubscriptionResetCardUsageQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GrantID int64 `json:"grant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionResetCardUsage.Query().
//		GroupBy(subscriptionresetcardusage.FieldGrantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardUsageQuery) GroupBy(field string, fields ...string) *SubscriptionResetCardUsageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionResetCardUsageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionresetcardusage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GrantID int64 `json:"grant_id,omitempty"`
//	}
//
//	client.SubscriptionResetCardUsage.Query().
//		Select(subscriptionresetcardusage.FieldGrantID).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardUsageQuery) Select(fields ...string) *SubscriptionResetCardUsageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionResetCardUsageSelect{SubscriptionResetCardUsageQuery: _q}
	sbuild.label = subscriptionresetcardusage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionResetCardUsageSelect configured with the given aggregations.
func (_q *SubscriptionResetCardUsageQuery) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardUsageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionResetCardUsageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionresetcardusage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionResetCardUsageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionResetCardUsage, error) {
	var (
		nodes       = []*SubscriptionResetCardUsage{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withGrant != nil,
			_q.withSubscription != nil,
			_q.withUser != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionResetCardUsage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionResetCardUsage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGrant; query != nil {
		if err := _q.loadGrant(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardUsage, e *SubscriptionResetCardGrant) { n.Edges.Grant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscription; query != nil {
		if err := _q.loadSubscription(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardUsage, e *UserSubscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardUsage, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardUsage, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionResetCardUsageQuery) loadGrant(ctx context.Context, query *SubscriptionResetCardGrantQuery, nodes []*SubscriptionResetCardUsage, init func(*SubscriptionResetCardUsage), assign func(*SubscriptionResetCardUsage, *SubscriptionResetCardGrant)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardUsage)
	for i := range nodes {
		fk := nodes[i].GrantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscriptionresetcardgrant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "grant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardUsageQuery) loadSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*SubscriptionResetCardUsage, init func(*SubscriptionResetCardUsage), assign func(*SubscriptionResetCardUsage, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardUsage)
	for i := range nodes {
		fk := nodes[i].SubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardUsageQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SubscriptionResetCardUsage, init func(*SubscriptionResetCardUsage), assign func(*SubscriptionResetCardUsage, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardUsage)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardUsageQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*SubscriptionResetCardUsage, init func(*SubscriptionResetCardUsage), assign func(*SubscriptionResetCardUsage, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardUsage)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SubscriptionResetCardUsageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionResetCardUsageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionresetcardusage.Table, subscriptionresetcardusage.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcardusage.FieldID)
		for i := range fields {
			if fields[i] != subscriptionresetcardusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGrant != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardusage.FieldGrantID)
		}
		if _q.withSubscription != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardusage.FieldSubscriptionID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardusage.FieldUserID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardusage.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionResetCardUsageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionresetcardusage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionresetcardusage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionResetCardUsageQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionResetCardUsageQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionResetCardUsageQuery) ForShare(opts ...sql.LockOption) *SubscriptionResetCardUsageQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionResetCardUsageGroupBy is the group-by builder for SubscriptionResetCardUsage entities.
type SubscriptionResetCardUsageGroupBy struct {
	selector
	build *SubscriptionResetCardUsageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionResetCardUsageGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardUsageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionResetCardUsageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardUsageQuery, *SubscriptionResetCardUsageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionResetCardUsageGroupBy) sqlScan(ctx context.Context, root *SubscriptionResetCardUsageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionResetCardUsageSelect is the builder for selecting fields of SubscriptionResetCardUsage entities.
type SubscriptionResetCardUsageSelect struct {
	*SubscriptionResetCardUsageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionResetCardUsageSelect) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardUsageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionResetCardUsageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardUsageQuery, *SubscriptionResetCardUsageSelect](ctx, _s.SubscriptionResetCardUsageQuery, _s, _s.inters, v)
}

func (_s *SubscriptionResetCardUsageSelect) sqlScan(ctx context.Context, root *SubscriptionResetCardUsageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
