// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardUsage is the model entity for the SubscriptionResetCardUsage schema.
type SubscriptionResetCardUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GrantID holds the value of the "grant_id" field.
	GrantID int64 `json:"grant_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// PreviousDailyUsageUsd holds the value of the "previous_daily_usage_usd" field.
	PreviousDailyUsageUsd float64 `json:"previous_daily_usage_usd,omitempty"`
	// PreviousWeeklyUsageUsd holds the value of the "previous_weekly_usage_usd" field.
	PreviousWeeklyUsageUsd float64 `json:"previous_weekly_usage_usd,omitempty"`
	// PreviousMonthlyUsageUsd holds the value of the "previous_monthly_usage_usd" field.
	PreviousMonthlyUsageUsd float64 `json:"previous_monthly_usage_usd,omitempty"`
	// PreviousDailyWindowStart holds the value of the "previous_daily_window_start" field.
	PreviousDailyWindowStart *time.Time `json:"previous_daily_window_start,omitempty"`
	// PreviousWeeklyWindowStart holds the value of the "previous_weekly_window_start" field.
	PreviousWeeklyWindowStart *time.Time `json:"previous_weekly_window_start,omitempty"`
	// PreviousMonthlyWindowStart holds the value of the "previous_monthly_window_start" field.
	PreviousMonthlyWindowStart *time.Time `json:"previous_monthly_window_start,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt time.Time `json:"used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionResetCardUsageQuery when eager-loading is set.
	Edges        SubscriptionResetCardUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionResetCardUsageEdges holds the relations/edges for other nodes in the graph.
type SubscriptionResetCardUsageEdges struct {
	// Grant holds the value of the grant edge.
	Grant *SubscriptionResetCardGrant `json:"grant,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// GrantOrErr returns the Grant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardUsageEdges) GrantOrErr() (*SubscriptionResetCardGrant, error) {
	if e.Grant != nil {
		return e.Grant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscriptionresetcardgrant.Label}
	}
	return nil, &NotLoadedError{edge: "grant"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardUsageEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardUsageEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionResetCardUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcardusage.FieldPreviousDailyUsageUsd, subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptionresetcardusage.FieldID, subscriptionresetcardusage.FieldGrantID, subscriptionresetcardusage.FieldSubscriptionID, subscriptionresetcardusage.FieldUserID, subscriptionresetcardusage.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case subscriptionresetcardusage.FieldMode, subscriptionresetcardusage.FieldRequestID:
			values[i] = new(sql.NullString)
		case subscriptionresetcardusage.FieldPreviousDailyWindowStart, subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, subscriptionresetcardusage.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionResetCardUsage fields.
func (_m *SubscriptionResetCardUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcardusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionresetcardusage.FieldGrantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_id", values[i])
			} else if value.Valid {
				_m.GrantID = value.Int64
			}
		case subscriptionresetcardusage.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionresetcardusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionresetcardusage.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionresetcardusage.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case subscriptionresetcardusage.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case subscriptionresetcardusage.FieldPreviousDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field previous_daily_usage_usd", values[i])
			} else if value.Valid {
				_m.PreviousDailyUsageUsd = value.Float64
			}
		case subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field previous_weekly_usage_usd", values[i])
			} else if value.Valid {
				_m.PreviousWeeklyUsageUsd = value.Float64
			}
		case subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field previous_monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.PreviousMonthlyUsageUsd = value.Float64
			}
		case subscriptionresetcardusage.FieldPreviousDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field previous_daily_window_start", values[i])
			} else if value.Valid {
				_m.PreviousDailyWindowStart = new(time.Time)
				*_m.PreviousDailyWindowStart = value.Time
			}
		case subscriptionresetcardusage.FieldPreviousWeeklyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field previous_weekly_window_start", values[i])
			} else if value.Valid {
				_m.PreviousWeeklyWindowStart = new(time.Time)
				*_m.PreviousWeeklyWindowStart = value.Time
			}
		case subscriptionresetcardusage.FieldPreviousMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field previous_monthly_window_start", values[i])
			} else if value.Valid {
				_m.PreviousMonthlyWindowStart = new(time.Time)
				*_m.PreviousMonthlyWindowStart = value.Time
			}
		case subscriptionresetcardusage.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionResetCardUsage.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionResetCardUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGrant queries the "grant" edge of the SubscriptionResetCardUsage entity.
func (_m *SubscriptionResetCardUsage) QueryGrant() *SubscriptionResetCardGrantQuery {
	return NewSubscriptionResetCardUsageClient(_m.config).QueryGrant(_m)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionResetCardUsage entity.
func (_m *SubscriptionResetCardUsage) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionResetCardUsageClient(_m.config).QuerySubscription(_m)
}

// QueryUser queries the "user" edge of the SubscriptionResetCardUsage entity.
func (_m *SubscriptionResetCardUsage) QueryUser() *UserQuery {
	return NewSubscriptionResetCardUsageClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionResetCardUsage entity.
func (_m *SubscriptionResetCardUsage) QueryGroup() *GroupQuery {
	return NewSubscriptionResetCardUsageClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this SubscriptionResetCardUsage.
// Note that you need to call SubscriptionResetCardUsage.Unwrap() before calling this method if this SubscriptionResetCardUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionResetCardUsage) Update() *SubscriptionResetCardUsageUpdateOne {
	return NewSubscriptionResetCardUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionResetCardUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionResetCardUsage) Unwrap() *SubscriptionResetCardUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionResetCardUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionResetCardUsage) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionResetCardUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("previous_daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreviousDailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("previous_weekly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreviousWeeklyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("previous_monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreviousMonthlyUsageUsd))
	builder.WriteString(", ")
	if v := _m.PreviousDailyWindowStart; v != nil {
		builder.WriteString("previous_daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PreviousWeeklyWindowStart; v != nil {
		builder.WriteString("previous_weekly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PreviousMonthlyWindowStart; v != nil {
		builder.WriteString("previous_monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("used_at=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionResetCardUsages is a parsable slice of SubscriptionResetCardUsage.
type SubscriptionResetCardUsages []*SubscriptionResetCardUsage
