// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetpreference"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetPreferenceCreate is the builder for creating a SubscriptionResetPreference entity.
type SubscriptionResetPreferenceCreate struct {
	config
	mutation *SubscriptionResetPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionResetPreferenceCreate) SetCreatedAt(v time.Time) *SubscriptionResetPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionResetPreferenceCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionResetPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionResetPreferenceCreate) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionResetPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionResetPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionResetPreferenceCreate) SetUserID(v int64) *SubscriptionResetPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionResetPreferenceCreate) SetGroupID(v int64) *SubscriptionResetPreferenceCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (_c *SubscriptionResetPreferenceCreate) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceCreate {
	_c.mutation.SetAutoUseEnabled(v)
	return _c
}

// SetNillableAutoUseEnabled sets the "auto_use_enabled" field if the given value is not nil.
func (_c *SubscriptionResetPreferenceCreate) SetNillableAutoUseEnabled(v *bool) *SubscriptionResetPreferenceCreate {
	if v != nil {
		_c.SetAutoUseEnabled(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionResetPreferenceCreate) SetUser(v *User) *SubscriptionResetPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionResetPreferenceCreate) SetGroup(v *Group) *SubscriptionResetPreferenceCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetPreferenceMutation object of the builder.
func (_c *SubscriptionResetPreferenceCreate) Mutation() *SubscriptionResetPreferenceMutation {
	return _c.mutation
}

// Save creates the SubscriptionResetPreference in the database.
func (_c *SubscriptionResetPreferenceCreate) Save(ctx context.Context) (*SubscriptionResetPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionResetPreferenceCreate) SaveX(ctx context.Context) *SubscriptionResetPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionResetPreferenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionresetpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionresetpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AutoUseEnabled(); !ok {
		v := subscriptionresetpreference.DefaultAutoUseEnabled
		_c.mutation.SetAutoUseEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionResetPreferenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionResetPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionResetPreference.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionResetPreference.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionResetPreference.group_id"`)}
	}
	if _, ok := _c.mutation.AutoUseEnabled(); !ok {
		return &ValidationError{Name: "auto_use_enabled", err: errors.New(`ent: missing required field "SubscriptionResetPreference.auto_use_enabled"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionResetPreference.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionResetPreference.group"`)}
	}
	return nil
}

func (_c *SubscriptionResetPreferenceCreate) sqlSave(ctx context.Context) (*SubscriptionResetPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionResetPreferenceCreate) createSpec() (*SubscriptionResetPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionResetPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionresetpreference.Table, sqlgraph.NewFieldSpec(subscriptionresetpreference.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionresetpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AutoUseEnabled(); ok {
		_spec.SetField(subscriptionresetpreference.FieldAutoUseEnabled, field.TypeBool, value)
		_node.AutoUseEnabled = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.UserTable,
			Columns: []string{subscriptionresetpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetpreference.GroupTable,
			Columns: []string{subscriptionresetpreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetPreferenceUpsertOne {
	_c.conflict = opts
	return &SubscriptionResetPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetPreferenceCreate) OnConflictColumns(columns ...string) *SubscriptionResetPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionResetPreferenceUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionResetPreference node.
	SubscriptionResetPreferenceUpsertOne struct {
		create *SubscriptionResetPreferenceCreate
	}

	// SubscriptionResetPreferenceUpsert is the "OnConflict" setter.
	SubscriptionResetPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetPreferenceUpsert) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceUpsert {
	u.Set(subscriptionresetpreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsert) UpdateUpdatedAt() *SubscriptionResetPreferenceUpsert {
	u.SetExcluded(subscriptionresetpreference.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetPreferenceUpsert) SetUserID(v int64) *SubscriptionResetPreferenceUpsert {
	u.Set(subscriptionresetpreference.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsert) UpdateUserID() *SubscriptionResetPreferenceUpsert {
	u.SetExcluded(subscriptionresetpreference.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetPreferenceUpsert) SetGroupID(v int64) *SubscriptionResetPreferenceUpsert {
	u.Set(subscriptionresetpreference.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsert) UpdateGroupID() *SubscriptionResetPreferenceUpsert {
	u.SetExcluded(subscriptionresetpreference.FieldGroupID)
	return u
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (u *SubscriptionResetPreferenceUpsert) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceUpsert {
	u.Set(subscriptionresetpreference.FieldAutoUseEnabled, v)
	return u
}

// UpdateAutoUseEnabled sets the "auto_use_enabled" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsert) UpdateAutoUseEnabled() *SubscriptionResetPreferenceUpsert {
	u.SetExcluded(subscriptionresetpreference.FieldAutoUseEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetPreferenceUpsertOne) UpdateNewValues() *SubscriptionResetPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionresetpreference.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionResetPreferenceUpsertOne) Ignore() *SubscriptionResetPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetPreferenceUpsertOne) DoNothing() *SubscriptionResetPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetPreferenceCreate.OnConflict
// documentation for more info.
func (u *SubscriptionResetPreferenceUpsertOne) Update(set func(*SubscriptionResetPreferenceUpsert)) *SubscriptionResetPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetPreferenceUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertOne) UpdateUpdatedAt() *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetPreferenceUpsertOne) SetUserID(v int64) *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertOne) UpdateUserID() *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetPreferenceUpsertOne) SetGroupID(v int64) *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertOne) UpdateGroupID() *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateGroupID()
	})
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (u *SubscriptionResetPreferenceUpsertOne) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetAutoUseEnabled(v)
	})
}

// UpdateAutoUseEnabled sets the "auto_use_enabled" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertOne) UpdateAutoUseEnabled() *SubscriptionResetPreferenceUpsertOne {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateAutoUseEnabled()
	})
}

// Exec executes the query.
func (u *SubscriptionResetPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionResetPreferenceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionResetPreferenceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionResetPreferenceCreateBulk is the builder for creating many SubscriptionResetPreference entities in bulk.
type SubscriptionResetPreferenceCreateBulk struct {
	config
	err      error
	builders []*SubscriptionResetPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionResetPreference entities in the database.
func (_c *SubscriptionResetPreferenceCreateBulk) Save(ctx context.Context) ([]*SubscriptionResetPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionResetPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionResetPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionResetPreferenceCreateBulk) SaveX(ctx context.Context) []*SubscriptionResetPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetPreferenceUpsertBulk {
	_c.conflict = opts
	return &SubscriptionResetPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetPreferenceCreateBulk) OnConflictColumns(columns ...string) *SubscriptionResetPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetPreferenceUpsertBulk{
		create: _c,
	}
}

// SubscriptionResetPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionResetPreference nodes.
type SubscriptionResetPreferenceUpsertBulk struct {
	create *SubscriptionResetPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetPreferenceUpsertBulk) UpdateNewValues() *SubscriptionResetPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionresetpreference.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionResetPreferenceUpsertBulk) Ignore() *SubscriptionResetPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetPreferenceUpsertBulk) DoNothing() *SubscriptionResetPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionResetPreferenceUpsertBulk) Update(set func(*SubscriptionResetPreferenceUpsert)) *SubscriptionResetPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertBulk) UpdateUpdatedAt() *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetPreferenceUpsertBulk) SetUserID(v int64) *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertBulk) UpdateUserID() *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetPreferenceUpsertBulk) SetGroupID(v int64) *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertBulk) UpdateGroupID() *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateGroupID()
	})
}

// SetAutoUseEnabled sets the "auto_use_enabled" field.
func (u *SubscriptionResetPreferenceUpsertBulk) SetAutoUseEnabled(v bool) *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.SetAutoUseEnabled(v)
	})
}

// UpdateAutoUseEnabled sets the "auto_use_enabled" field to the value that was provided on create.
func (u *SubscriptionResetPreferenceUpsertBulk) UpdateAutoUseEnabled() *SubscriptionResetPreferenceUpsertBulk {
	return u.Update(func(s *SubscriptionResetPreferenceUpsert) {
		s.UpdateAutoUseEnabled()
	})
}

// Exec executes the query.
func (u *SubscriptionResetPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionResetPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
