// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardUsageCreate is the builder for creating a SubscriptionResetCardUsage entity.
type SubscriptionResetCardUsageCreate struct {
	config
	mutation *SubscriptionResetCardUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGrantID sets the "grant_id" field.
func (_c *SubscriptionResetCardUsageCreate) SetGrantID(v int64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionResetCardUsageCreate) SetSubscriptionID(v int64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionResetCardUsageCreate) SetUserID(v int64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionResetCardUsageCreate) SetGroupID(v int64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *SubscriptionResetCardUsageCreate) SetMode(v string) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *SubscriptionResetCardUsageCreate) SetRequestID(v string) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillableRequestID(v *string) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousDailyUsageUsd(v)
	return _c
}

// SetNillablePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousDailyUsageUsd(v *float64) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousDailyUsageUsd(*v)
	}
	return _c
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousWeeklyUsageUsd(v)
	return _c
}

// SetNillablePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousWeeklyUsageUsd(v *float64) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousWeeklyUsageUsd(*v)
	}
	return _c
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousMonthlyUsageUsd(v)
	return _c
}

// SetNillablePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousMonthlyUsageUsd(v *float64) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousMonthlyUsageUsd(*v)
	}
	return _c
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousDailyWindowStart(v)
	return _c
}

// SetNillablePreviousDailyWindowStart sets the "previous_daily_window_start" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousDailyWindowStart(v *time.Time) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousDailyWindowStart(*v)
	}
	return _c
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousWeeklyWindowStart(v)
	return _c
}

// SetNillablePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousWeeklyWindowStart(v *time.Time) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousWeeklyWindowStart(*v)
	}
	return _c
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (_c *SubscriptionResetCardUsageCreate) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetPreviousMonthlyWindowStart(v)
	return _c
}

// SetNillablePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillablePreviousMonthlyWindowStart(v *time.Time) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetPreviousMonthlyWindowStart(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *SubscriptionResetCardUsageCreate) SetUsedAt(v time.Time) *SubscriptionResetCardUsageCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *SubscriptionResetCardUsageCreate) SetNillableUsedAt(v *time.Time) *SubscriptionResetCardUsageCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetGrant sets the "grant" edge to the SubscriptionResetCardGrant entity.
func (_c *SubscriptionResetCardUsageCreate) SetGrant(v *SubscriptionResetCardGrant) *SubscriptionResetCardUsageCreate {
	return _c.SetGrantID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionResetCardUsageCreate) SetSubscription(v *UserSubscription) *SubscriptionResetCardUsageCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionResetCardUsageCreate) SetUser(v *User) *SubscriptionResetCardUsageCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionResetCardUsageCreate) SetGroup(v *Group) *SubscriptionResetCardUsageCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionResetCardUsageMutation object of the builder.
func (_c *SubscriptionResetCardUsageCreate) Mutation() *SubscriptionResetCardUsageMutation {
	return _c.mutation
}

// Save creates the SubscriptionResetCardUsage in the database.
func (_c *SubscriptionResetCardUsageCreate) Save(ctx context.Context) (*SubscriptionResetCardUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionResetCardUsageCreate) SaveX(ctx context.Context) *SubscriptionResetCardUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetCardUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetCardUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionResetCardUsageCreate) defaults() {
	if _, ok := _c.mutation.PreviousDailyUsageUsd(); !ok {
		v := subscriptionresetcardusage.DefaultPreviousDailyUsageUsd
		_c.mutation.SetPreviousDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.PreviousWeeklyUsageUsd(); !ok {
		v := subscriptionresetcardusage.DefaultPreviousWeeklyUsageUsd
		_c.mutation.SetPreviousWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.PreviousMonthlyUsageUsd(); !ok {
		v := subscriptionresetcardusage.DefaultPreviousMonthlyUsageUsd
		_c.mutation.SetPreviousMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		v := subscriptionresetcardusage.DefaultUsedAt()
		_c.mutation.SetUsedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionResetCardUsageCreate) check() error {
	if _, ok := _c.mutation.GrantID(); !ok {
		return &ValidationError{Name: "grant_id", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.grant_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.subscription_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.group_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := subscriptionresetcardusage.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.mode": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := subscriptionresetcardusage.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardUsage.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PreviousDailyUsageUsd(); !ok {
		return &ValidationError{Name: "previous_daily_usage_usd", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.previous_daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.PreviousWeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "previous_weekly_usage_usd", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.previous_weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.PreviousMonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "previous_monthly_usage_usd", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.previous_monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		return &ValidationError{Name: "used_at", err: errors.New(`ent: missing required field "SubscriptionResetCardUsage.used_at"`)}
	}
	if len(_c.mutation.GrantIDs()) == 0 {
		return &ValidationError{Name: "grant", err: errors.New(`ent: missing required edge "SubscriptionResetCardUsage.grant"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionResetCardUsage.subscription"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionResetCardUsage.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionResetCardUsage.group"`)}
	}
	return nil
}

func (_c *SubscriptionResetCardUsageCreate) sqlSave(ctx context.Context) (*SubscriptionResetCardUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionResetCardUsageCreate) createSpec() (*SubscriptionResetCardUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionResetCardUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionresetcardusage.Table, sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.PreviousDailyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, field.TypeFloat64, value)
		_node.PreviousDailyUsageUsd = value
	}
	if value, ok := _c.mutation.PreviousWeeklyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, field.TypeFloat64, value)
		_node.PreviousWeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.PreviousMonthlyUsageUsd(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, field.TypeFloat64, value)
		_node.PreviousMonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.PreviousDailyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousDailyWindowStart, field.TypeTime, value)
		_node.PreviousDailyWindowStart = &value
	}
	if value, ok := _c.mutation.PreviousWeeklyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, field.TypeTime, value)
		_node.PreviousWeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.PreviousMonthlyWindowStart(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, field.TypeTime, value)
		_node.PreviousMonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(subscriptionresetcardusage.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = value
	}
	if nodes := _c.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GrantTable,
			Columns: []string{subscriptionresetcardusage.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.SubscriptionTable,
			Columns: []string{subscriptionresetcardusage.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.UserTable,
			Columns: []string{subscriptionresetcardusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardusage.GroupTable,
			Columns: []string{subscriptionresetcardusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetCardUsage.Create().
//		SetGrantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetCardUsageUpsert) {
//			SetGrantID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetCardUsageCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetCardUsageUpsertOne {
	_c.conflict = opts
	return &SubscriptionResetCardUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetCardUsageCreate) OnConflictColumns(columns ...string) *SubscriptionResetCardUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetCardUsageUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionResetCardUsageUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionResetCardUsage node.
	SubscriptionResetCardUsageUpsertOne struct {
		create *SubscriptionResetCardUsageCreate
	}

	// SubscriptionResetCardUsageUpsert is the "OnConflict" setter.
	SubscriptionResetCardUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetGrantID sets the "grant_id" field.
func (u *SubscriptionResetCardUsageUpsert) SetGrantID(v int64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateGrantID() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldGrantID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionResetCardUsageUpsert) SetSubscriptionID(v int64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateSubscriptionID() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldSubscriptionID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardUsageUpsert) SetUserID(v int64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateUserID() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardUsageUpsert) SetGroupID(v int64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateGroupID() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldGroupID)
	return u
}

// SetMode sets the "mode" field.
func (u *SubscriptionResetCardUsageUpsert) SetMode(v string) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateMode() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldMode)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionResetCardUsageUpsert) SetRequestID(v string) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdateRequestID() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SubscriptionResetCardUsageUpsert) ClearRequestID() *SubscriptionResetCardUsageUpsert {
	u.SetNull(subscriptionresetcardusage.FieldRequestID)
	return u
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, v)
	return u
}

// UpdatePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousDailyUsageUsd() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousDailyUsageUsd)
	return u
}

// AddPreviousDailyUsageUsd adds v to the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) AddPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Add(subscriptionresetcardusage.FieldPreviousDailyUsageUsd, v)
	return u
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, v)
	return u
}

// UpdatePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousWeeklyUsageUsd() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd)
	return u
}

// AddPreviousWeeklyUsageUsd adds v to the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) AddPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Add(subscriptionresetcardusage.FieldPreviousWeeklyUsageUsd, v)
	return u
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, v)
	return u
}

// UpdatePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousMonthlyUsageUsd() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd)
	return u
}

// AddPreviousMonthlyUsageUsd adds v to the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsert) AddPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsert {
	u.Add(subscriptionresetcardusage.FieldPreviousMonthlyUsageUsd, v)
	return u
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousDailyWindowStart, v)
	return u
}

// UpdatePreviousDailyWindowStart sets the "previous_daily_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousDailyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousDailyWindowStart)
	return u
}

// ClearPreviousDailyWindowStart clears the value of the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) ClearPreviousDailyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetNull(subscriptionresetcardusage.FieldPreviousDailyWindowStart)
	return u
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart, v)
	return u
}

// UpdatePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart)
	return u
}

// ClearPreviousWeeklyWindowStart clears the value of the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) ClearPreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetNull(subscriptionresetcardusage.FieldPreviousWeeklyWindowStart)
	return u
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsert {
	u.Set(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart, v)
	return u
}

// UpdatePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsert) UpdatePreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetExcluded(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart)
	return u
}

// ClearPreviousMonthlyWindowStart clears the value of the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsert) ClearPreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsert {
	u.SetNull(subscriptionresetcardusage.FieldPreviousMonthlyWindowStart)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetCardUsageUpsertOne) UpdateNewValues() *SubscriptionResetCardUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.UsedAt(); exists {
			s.SetIgnore(subscriptionresetcardusage.FieldUsedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionResetCardUsageUpsertOne) Ignore() *SubscriptionResetCardUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetCardUsageUpsertOne) DoNothing() *SubscriptionResetCardUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetCardUsageCreate.OnConflict
// documentation for more info.
func (u *SubscriptionResetCardUsageUpsertOne) Update(set func(*SubscriptionResetCardUsageUpsert)) *SubscriptionResetCardUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetCardUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetGrantID(v int64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateGrantID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateGrantID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetSubscriptionID(v int64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateSubscriptionID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetUserID(v int64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateUserID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetGroupID(v int64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateGroupID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetMode(v string) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateMode() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateMode()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetRequestID(v string) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdateRequestID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SubscriptionResetCardUsageUpsertOne) ClearRequestID() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearRequestID()
	})
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousDailyUsageUsd(v)
	})
}

// AddPreviousDailyUsageUsd adds v to the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) AddPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousDailyUsageUsd(v)
	})
}

// UpdatePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousDailyUsageUsd() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousDailyUsageUsd()
	})
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousWeeklyUsageUsd(v)
	})
}

// AddPreviousWeeklyUsageUsd adds v to the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) AddPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousWeeklyUsageUsd(v)
	})
}

// UpdatePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousWeeklyUsageUsd() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousWeeklyUsageUsd()
	})
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousMonthlyUsageUsd(v)
	})
}

// AddPreviousMonthlyUsageUsd adds v to the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertOne) AddPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousMonthlyUsageUsd(v)
	})
}

// UpdatePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousMonthlyUsageUsd() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousMonthlyUsageUsd()
	})
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousDailyWindowStart(v)
	})
}

// UpdatePreviousDailyWindowStart sets the "previous_daily_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousDailyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousDailyWindowStart()
	})
}

// ClearPreviousDailyWindowStart clears the value of the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) ClearPreviousDailyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousDailyWindowStart()
	})
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousWeeklyWindowStart(v)
	})
}

// UpdatePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousWeeklyWindowStart()
	})
}

// ClearPreviousWeeklyWindowStart clears the value of the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) ClearPreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousWeeklyWindowStart()
	})
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousMonthlyWindowStart(v)
	})
}

// UpdatePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertOne) UpdatePreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousMonthlyWindowStart()
	})
}

// ClearPreviousMonthlyWindowStart clears the value of the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertOne) ClearPreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsertOne {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *SubscriptionResetCardUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetCardUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetCardUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionResetCardUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionResetCardUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionResetCardUsageCreateBulk is the builder for creating many SubscriptionResetCardUsage entities in bulk.
type SubscriptionResetCardUsageCreateBulk struct {
	config
	err      error
	builders []*SubscriptionResetCardUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionResetCardUsage entities in the database.
func (_c *SubscriptionResetCardUsageCreateBulk) Save(ctx context.Context) ([]*SubscriptionResetCardUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionResetCardUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionResetCardUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionResetCardUsageCreateBulk) SaveX(ctx context.Context) []*SubscriptionResetCardUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetCardUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetCardUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetCardUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetCardUsageUpsert) {
//			SetGrantID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetCardUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetCardUsageUpsertBulk {
	_c.conflict = opts
	return &SubscriptionResetCardUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetCardUsageCreateBulk) OnConflictColumns(columns ...string) *SubscriptionResetCardUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetCardUsageUpsertBulk{
		create: _c,
	}
}

// SubscriptionResetCardUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionResetCardUsage nodes.
type SubscriptionResetCardUsageUpsertBulk struct {
	create *SubscriptionResetCardUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateNewValues() *SubscriptionResetCardUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.UsedAt(); exists {
				s.SetIgnore(subscriptionresetcardusage.FieldUsedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionResetCardUsageUpsertBulk) Ignore() *SubscriptionResetCardUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetCardUsageUpsertBulk) DoNothing() *SubscriptionResetCardUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetCardUsageCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionResetCardUsageUpsertBulk) Update(set func(*SubscriptionResetCardUsageUpsert)) *SubscriptionResetCardUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetCardUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetGrantID(v int64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateGrantID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateGrantID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetSubscriptionID(v int64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateSubscriptionID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetUserID(v int64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateUserID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetGroupID(v int64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateGroupID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetMode(v string) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateMode() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateMode()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetRequestID(v string) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdateRequestID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SubscriptionResetCardUsageUpsertBulk) ClearRequestID() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearRequestID()
	})
}

// SetPreviousDailyUsageUsd sets the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousDailyUsageUsd(v)
	})
}

// AddPreviousDailyUsageUsd adds v to the "previous_daily_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) AddPreviousDailyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousDailyUsageUsd(v)
	})
}

// UpdatePreviousDailyUsageUsd sets the "previous_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousDailyUsageUsd() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousDailyUsageUsd()
	})
}

// SetPreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousWeeklyUsageUsd(v)
	})
}

// AddPreviousWeeklyUsageUsd adds v to the "previous_weekly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) AddPreviousWeeklyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousWeeklyUsageUsd(v)
	})
}

// UpdatePreviousWeeklyUsageUsd sets the "previous_weekly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousWeeklyUsageUsd() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousWeeklyUsageUsd()
	})
}

// SetPreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousMonthlyUsageUsd(v)
	})
}

// AddPreviousMonthlyUsageUsd adds v to the "previous_monthly_usage_usd" field.
func (u *SubscriptionResetCardUsageUpsertBulk) AddPreviousMonthlyUsageUsd(v float64) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.AddPreviousMonthlyUsageUsd(v)
	})
}

// UpdatePreviousMonthlyUsageUsd sets the "previous_monthly_usage_usd" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousMonthlyUsageUsd() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousMonthlyUsageUsd()
	})
}

// SetPreviousDailyWindowStart sets the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousDailyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousDailyWindowStart(v)
	})
}

// UpdatePreviousDailyWindowStart sets the "previous_daily_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousDailyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousDailyWindowStart()
	})
}

// ClearPreviousDailyWindowStart clears the value of the "previous_daily_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) ClearPreviousDailyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousDailyWindowStart()
	})
}

// SetPreviousWeeklyWindowStart sets the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousWeeklyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousWeeklyWindowStart(v)
	})
}

// UpdatePreviousWeeklyWindowStart sets the "previous_weekly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousWeeklyWindowStart()
	})
}

// ClearPreviousWeeklyWindowStart clears the value of the "previous_weekly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) ClearPreviousWeeklyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousWeeklyWindowStart()
	})
}

// SetPreviousMonthlyWindowStart sets the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) SetPreviousMonthlyWindowStart(v time.Time) *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.SetPreviousMonthlyWindowStart(v)
	})
}

// UpdatePreviousMonthlyWindowStart sets the "previous_monthly_window_start" field to the value that was provided on create.
func (u *SubscriptionResetCardUsageUpsertBulk) UpdatePreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.UpdatePreviousMonthlyWindowStart()
	})
}

// ClearPreviousMonthlyWindowStart clears the value of the "previous_monthly_window_start" field.
func (u *SubscriptionResetCardUsageUpsertBulk) ClearPreviousMonthlyWindowStart() *SubscriptionResetCardUsageUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardUsageUpsert) {
		s.ClearPreviousMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *SubscriptionResetCardUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionResetCardUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetCardUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetCardUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
