// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetCardGrant is the model entity for the SubscriptionResetCardGrant schema.
type SubscriptionResetCardGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// IssuedCount holds the value of the "issued_count" field.
	IssuedCount int `json:"issued_count,omitempty"`
	// RemainingCount holds the value of the "remaining_count" field.
	RemainingCount int `json:"remaining_count,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Internal idempotency recovery identifier; never exposed by the API
	RequestID *string `json:"request_id,omitempty"`
	// IssuedBy holds the value of the "issued_by" field.
	IssuedBy *int64 `json:"issued_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionResetCardGrantQuery when eager-loading is set.
	Edges        SubscriptionResetCardGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionResetCardGrantEdges holds the relations/edges for other nodes in the graph.
type SubscriptionResetCardGrantEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Issuer holds the value of the issuer edge.
	Issuer *User `json:"issuer,omitempty"`
	// Usages holds the value of the usages edge.
	Usages []*SubscriptionResetCardUsage `json:"usages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardGrantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardGrantEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// IssuerOrErr returns the Issuer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardGrantEdges) IssuerOrErr() (*User, error) {
	if e.Issuer != nil {
		return e.Issuer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "issuer"}
}

// UsagesOrErr returns the Usages value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionResetCardGrantEdges) UsagesOrErr() ([]*SubscriptionResetCardUsage, error) {
	if e.loadedTypes[3] {
		return e.Usages, nil
	}
	return nil, &NotLoadedError{edge: "usages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionResetCardGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcardgrant.FieldID, subscriptionresetcardgrant.FieldUserID, subscriptionresetcardgrant.FieldGroupID, subscriptionresetcardgrant.FieldIssuedCount, subscriptionresetcardgrant.FieldRemainingCount, subscriptionresetcardgrant.FieldIssuedBy:
			values[i] = new(sql.NullInt64)
		case subscriptionresetcardgrant.FieldStatus, subscriptionresetcardgrant.FieldSource, subscriptionresetcardgrant.FieldRequestID, subscriptionresetcardgrant.FieldNotes:
			values[i] = new(sql.NullString)
		case subscriptionresetcardgrant.FieldCreatedAt, subscriptionresetcardgrant.FieldUpdatedAt, subscriptionresetcardgrant.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionResetCardGrant fields.
func (_m *SubscriptionResetCardGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcardgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionresetcardgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionresetcardgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionresetcardgrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionresetcardgrant.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionresetcardgrant.FieldIssuedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issued_count", values[i])
			} else if value.Valid {
				_m.IssuedCount = int(value.Int64)
			}
		case subscriptionresetcardgrant.FieldRemainingCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_count", values[i])
			} else if value.Valid {
				_m.RemainingCount = int(value.Int64)
			}
		case subscriptionresetcardgrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case subscriptionresetcardgrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionresetcardgrant.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case subscriptionresetcardgrant.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case subscriptionresetcardgrant.FieldIssuedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issued_by", values[i])
			} else if value.Valid {
				_m.IssuedBy = new(int64)
				*_m.IssuedBy = value.Int64
			}
		case subscriptionresetcardgrant.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionResetCardGrant.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionResetCardGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionResetCardGrant entity.
func (_m *SubscriptionResetCardGrant) QueryUser() *UserQuery {
	return NewSubscriptionResetCardGrantClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionResetCardGrant entity.
func (_m *SubscriptionResetCardGrant) QueryGroup() *GroupQuery {
	return NewSubscriptionResetCardGrantClient(_m.config).QueryGroup(_m)
}

// QueryIssuer queries the "issuer" edge of the SubscriptionResetCardGrant entity.
func (_m *SubscriptionResetCardGrant) QueryIssuer() *UserQuery {
	return NewSubscriptionResetCardGrantClient(_m.config).QueryIssuer(_m)
}

// QueryUsages queries the "usages" edge of the SubscriptionResetCardGrant entity.
func (_m *SubscriptionResetCardGrant) QueryUsages() *SubscriptionResetCardUsageQuery {
	return NewSubscriptionResetCardGrantClient(_m.config).QueryUsages(_m)
}

// Update returns a builder for updating this SubscriptionResetCardGrant.
// Note that you need to call SubscriptionResetCardGrant.Unwrap() before calling this method if this SubscriptionResetCardGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionResetCardGrant) Update() *SubscriptionResetCardGrantUpdateOne {
	return NewSubscriptionResetCardGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionResetCardGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionResetCardGrant) Unwrap() *SubscriptionResetCardGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionResetCardGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionResetCardGrant) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionResetCardGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("issued_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssuedCount))
	builder.WriteString(", ")
	builder.WriteString("remaining_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemainingCount))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IssuedBy; v != nil {
		builder.WriteString("issued_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionResetCardGrants is a parsable slice of SubscriptionResetCardGrant.
type SubscriptionResetCardGrants []*SubscriptionResetCardGrant
