// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetpreference"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetPreference is the model entity for the SubscriptionResetPreference schema.
type SubscriptionResetPreference struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AutoUseEnabled holds the value of the "auto_use_enabled" field.
	AutoUseEnabled bool `json:"auto_use_enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionResetPreferenceQuery when eager-loading is set.
	Edges        SubscriptionResetPreferenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionResetPreferenceEdges holds the relations/edges for other nodes in the graph.
type SubscriptionResetPreferenceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetPreferenceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetPreferenceEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionResetPreference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionresetpreference.FieldAutoUseEnabled:
			values[i] = new(sql.NullBool)
		case subscriptionresetpreference.FieldID, subscriptionresetpreference.FieldUserID, subscriptionresetpreference.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case subscriptionresetpreference.FieldCreatedAt, subscriptionresetpreference.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionResetPreference fields.
func (_m *SubscriptionResetPreference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionresetpreference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionresetpreference.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionresetpreference.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionresetpreference.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionresetpreference.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionresetpreference.FieldAutoUseEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_use_enabled", values[i])
			} else if value.Valid {
				_m.AutoUseEnabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionResetPreference.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionResetPreference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionResetPreference entity.
func (_m *SubscriptionResetPreference) QueryUser() *UserQuery {
	return NewSubscriptionResetPreferenceClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionResetPreference entity.
func (_m *SubscriptionResetPreference) QueryGroup() *GroupQuery {
	return NewSubscriptionResetPreferenceClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this SubscriptionResetPreference.
// Note that you need to call SubscriptionResetPreference.Unwrap() before calling this method if this SubscriptionResetPreference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionResetPreference) Update() *SubscriptionResetPreferenceUpdateOne {
	return NewSubscriptionResetPreferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionResetPreference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionResetPreference) Unwrap() *SubscriptionResetPreference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionResetPreference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionResetPreference) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionResetPreference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("auto_use_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoUseEnabled))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionResetPreferences is a parsable slice of SubscriptionResetPreference.
type SubscriptionResetPreferences []*SubscriptionResetPreference
