// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetCardGrantUpdate is the builder for updating SubscriptionResetCardGrant entities.
type SubscriptionResetCardGrantUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionResetCardGrantMutation
}

// Where appends a list predicates to the SubscriptionResetCardGrantUpdate builder.
func (_u *SubscriptionResetCardGrantUpdate) Where(ps ...predicate.SubscriptionResetCardGrant) *SubscriptionResetCardGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetCardGrantUpdate) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardGrantUpdate) SetUserID(v int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableUserID(v *int64) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetCardGrantUpdate) SetGroupID(v int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableGroupID(v *int64) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetIssuedCount sets the "issued_count" field.
func (_u *SubscriptionResetCardGrantUpdate) SetIssuedCount(v int) *SubscriptionResetCardGrantUpdate {
	_u.mutation.ResetIssuedCount()
	_u.mutation.SetIssuedCount(v)
	return _u
}

// SetNillableIssuedCount sets the "issued_count" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableIssuedCount(v *int) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetIssuedCount(*v)
	}
	return _u
}

// AddIssuedCount adds value to the "issued_count" field.
func (_u *SubscriptionResetCardGrantUpdate) AddIssuedCount(v int) *SubscriptionResetCardGrantUpdate {
	_u.mutation.AddIssuedCount(v)
	return _u
}

// SetRemainingCount sets the "remaining_count" field.
func (_u *SubscriptionResetCardGrantUpdate) SetRemainingCount(v int) *SubscriptionResetCardGrantUpdate {
	_u.mutation.ResetRemainingCount()
	_u.mutation.SetRemainingCount(v)
	return _u
}

// SetNillableRemainingCount sets the "remaining_count" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableRemainingCount(v *int) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetRemainingCount(*v)
	}
	return _u
}

// AddRemainingCount adds value to the "remaining_count" field.
func (_u *SubscriptionResetCardGrantUpdate) AddRemainingCount(v int) *SubscriptionResetCardGrantUpdate {
	_u.mutation.AddRemainingCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionResetCardGrantUpdate) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionResetCardGrantUpdate) ClearExpiresAt() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionResetCardGrantUpdate) SetStatus(v string) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableStatus(v *string) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SubscriptionResetCardGrantUpdate) SetSource(v string) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableSource(v *string) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *SubscriptionResetCardGrantUpdate) SetIssuedBy(v int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableIssuedBy(v *int64) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *SubscriptionResetCardGrantUpdate) ClearIssuedBy() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionResetCardGrantUpdate) SetNotes(v string) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableNotes(v *string) *SubscriptionResetCardGrantUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionResetCardGrantUpdate) ClearNotes() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdate) SetUser(v *User) *SubscriptionResetCardGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetCardGrantUpdate) SetGroup(v *Group) *SubscriptionResetCardGrantUpdate {
	return _u.SetGroupID(v.ID)
}

// SetIssuerID sets the "issuer" edge to the User entity by ID.
func (_u *SubscriptionResetCardGrantUpdate) SetIssuerID(id int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.SetIssuerID(id)
	return _u
}

// SetNillableIssuerID sets the "issuer" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdate) SetNillableIssuerID(id *int64) *SubscriptionResetCardGrantUpdate {
	if id != nil {
		_u = _u.SetIssuerID(*id)
	}
	return _u
}

// SetIssuer sets the "issuer" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdate) SetIssuer(v *User) *SubscriptionResetCardGrantUpdate {
	return _u.SetIssuerID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the SubscriptionResetCardUsage entity by IDs.
func (_u *SubscriptionResetCardGrantUpdate) AddUsageIDs(ids ...int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the SubscriptionResetCardUsage entity.
func (_u *SubscriptionResetCardGrantUpdate) AddUsages(v ...*SubscriptionResetCardUsage) *SubscriptionResetCardGrantUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the SubscriptionResetCardGrantMutation object of the builder.
func (_u *SubscriptionResetCardGrantUpdate) Mutation() *SubscriptionResetCardGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdate) ClearUser() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetCardGrantUpdate) ClearGroup() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearIssuer clears the "issuer" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdate) ClearIssuer() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearIssuer()
	return _u
}

// ClearUsages clears all "usages" edges to the SubscriptionResetCardUsage entity.
func (_u *SubscriptionResetCardGrantUpdate) ClearUsages() *SubscriptionResetCardGrantUpdate {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to SubscriptionResetCardUsage entities by IDs.
func (_u *SubscriptionResetCardGrantUpdate) RemoveUsageIDs(ids ...int64) *SubscriptionResetCardGrantUpdate {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to SubscriptionResetCardUsage entities.
func (_u *SubscriptionResetCardGrantUpdate) RemoveUsages(v ...*SubscriptionResetCardUsage) *SubscriptionResetCardGrantUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionResetCardGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionResetCardGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetCardGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionresetcardgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardGrantUpdate) check() error {
	if v, ok := _u.mutation.IssuedCount(); ok {
		if err := subscriptionresetcardgrant.IssuedCountValidator(v); err != nil {
			return &ValidationError{Name: "issued_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.issued_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemainingCount(); ok {
		if err := subscriptionresetcardgrant.RemainingCountValidator(v); err != nil {
			return &ValidationError{Name: "remaining_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.remaining_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionresetcardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := subscriptionresetcardgrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardGrant.group"`)
	}
	return nil
}

func (_u *SubscriptionResetCardGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldIssuedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssuedCount(); ok {
		_spec.AddField(subscriptionresetcardgrant.FieldIssuedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemainingCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldRemainingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemainingCount(); ok {
		_spec.AddField(subscriptionresetcardgrant.FieldRemainingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldSource, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.UserTable,
			Columns: []string{subscriptionresetcardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.UserTable,
			Columns: []string{subscriptionresetcardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.GroupTable,
			Columns: []string{subscriptionresetcardgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.GroupTable,
			Columns: []string{subscriptionresetcardgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IssuerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.IssuerTable,
			Columns: []string{subscriptionresetcardgrant.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.IssuerTable,
			Columns: []string{subscriptionresetcardgrant.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcardgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionResetCardGrantUpdateOne is the builder for updating a single SubscriptionResetCardGrant entity.
type SubscriptionResetCardGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionResetCardGrantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetUserID(v int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableUserID(v *int64) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetGroupID(v int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableGroupID(v *int64) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetIssuedCount sets the "issued_count" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetIssuedCount(v int) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ResetIssuedCount()
	_u.mutation.SetIssuedCount(v)
	return _u
}

// SetNillableIssuedCount sets the "issued_count" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableIssuedCount(v *int) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetIssuedCount(*v)
	}
	return _u
}

// AddIssuedCount adds value to the "issued_count" field.
func (_u *SubscriptionResetCardGrantUpdateOne) AddIssuedCount(v int) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.AddIssuedCount(v)
	return _u
}

// SetRemainingCount sets the "remaining_count" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetRemainingCount(v int) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ResetRemainingCount()
	_u.mutation.SetRemainingCount(v)
	return _u
}

// SetNillableRemainingCount sets the "remaining_count" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableRemainingCount(v *int) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetRemainingCount(*v)
	}
	return _u
}

// AddRemainingCount adds value to the "remaining_count" field.
func (_u *SubscriptionResetCardGrantUpdateOne) AddRemainingCount(v int) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.AddRemainingCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearExpiresAt() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetStatus(v string) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableStatus(v *string) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetSource(v string) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableSource(v *string) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetIssuedBy(v int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableIssuedBy(v *int64) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearIssuedBy() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNotes(v string) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableNotes(v *string) *SubscriptionResetCardGrantUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearNotes() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdateOne) SetUser(v *User) *SubscriptionResetCardGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionResetCardGrantUpdateOne) SetGroup(v *Group) *SubscriptionResetCardGrantUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetIssuerID sets the "issuer" edge to the User entity by ID.
func (_u *SubscriptionResetCardGrantUpdateOne) SetIssuerID(id int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.SetIssuerID(id)
	return _u
}

// SetNillableIssuerID sets the "issuer" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionResetCardGrantUpdateOne) SetNillableIssuerID(id *int64) *SubscriptionResetCardGrantUpdateOne {
	if id != nil {
		_u = _u.SetIssuerID(*id)
	}
	return _u
}

// SetIssuer sets the "issuer" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdateOne) SetIssuer(v *User) *SubscriptionResetCardGrantUpdateOne {
	return _u.SetIssuerID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the SubscriptionResetCardUsage entity by IDs.
func (_u *SubscriptionResetCardGrantUpdateOne) AddUsageIDs(ids ...int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the SubscriptionResetCardUsage entity.
func (_u *SubscriptionResetCardGrantUpdateOne) AddUsages(v ...*SubscriptionResetCardUsage) *SubscriptionResetCardGrantUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the SubscriptionResetCardGrantMutation object of the builder.
func (_u *SubscriptionResetCardGrantUpdateOne) Mutation() *SubscriptionResetCardGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearUser() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearGroup() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearIssuer clears the "issuer" edge to the User entity.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearIssuer() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearIssuer()
	return _u
}

// ClearUsages clears all "usages" edges to the SubscriptionResetCardUsage entity.
func (_u *SubscriptionResetCardGrantUpdateOne) ClearUsages() *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to SubscriptionResetCardUsage entities by IDs.
func (_u *SubscriptionResetCardGrantUpdateOne) RemoveUsageIDs(ids ...int64) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to SubscriptionResetCardUsage entities.
func (_u *SubscriptionResetCardGrantUpdateOne) RemoveUsages(v ...*SubscriptionResetCardUsage) *SubscriptionResetCardGrantUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Where appends a list predicates to the SubscriptionResetCardGrantUpdate builder.
func (_u *SubscriptionResetCardGrantUpdateOne) Where(ps ...predicate.SubscriptionResetCardGrant) *SubscriptionResetCardGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionResetCardGrantUpdateOne) Select(field string, fields ...string) *SubscriptionResetCardGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionResetCardGrant entity.
func (_u *SubscriptionResetCardGrantUpdateOne) Save(ctx context.Context) (*SubscriptionResetCardGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardGrantUpdateOne) SaveX(ctx context.Context) *SubscriptionResetCardGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionResetCardGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetCardGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionresetcardgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardGrantUpdateOne) check() error {
	if v, ok := _u.mutation.IssuedCount(); ok {
		if err := subscriptionresetcardgrant.IssuedCountValidator(v); err != nil {
			return &ValidationError{Name: "issued_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.issued_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemainingCount(); ok {
		if err := subscriptionresetcardgrant.RemainingCountValidator(v); err != nil {
			return &ValidationError{Name: "remaining_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.remaining_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionresetcardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := subscriptionresetcardgrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCardGrant.group"`)
	}
	return nil
}

func (_u *SubscriptionResetCardGrantUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionResetCardGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionResetCardGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcardgrant.FieldID)
		for _, f := range fields {
			if !subscriptionresetcardgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionresetcardgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldIssuedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssuedCount(); ok {
		_spec.AddField(subscriptionresetcardgrant.FieldIssuedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemainingCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldRemainingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRemainingCount(); ok {
		_spec.AddField(subscriptionresetcardgrant.FieldRemainingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldSource, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionresetcardgrant.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.UserTable,
			Columns: []string{subscriptionresetcardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.UserTable,
			Columns: []string{subscriptionresetcardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.GroupTable,
			Columns: []string{subscriptionresetcardgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.GroupTable,
			Columns: []string{subscriptionresetcardgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IssuerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.IssuerTable,
			Columns: []string{subscriptionresetcardgrant.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.IssuerTable,
			Columns: []string{subscriptionresetcardgrant.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionResetCardGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcardgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
