// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetCardGrantQuery is the builder for querying SubscriptionResetCardGrant entities.
type SubscriptionResetCardGrantQuery struct {
	config
	ctx        *QueryContext
	order      []subscriptionresetcardgrant.OrderOption
	inters     []Interceptor
	predicates []predicate.SubscriptionResetCardGrant
	withUser   *UserQuery
	withGroup  *GroupQuery
	withIssuer *UserQuery
	withUsages *SubscriptionResetCardUsageQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionResetCardGrantQuery builder.
func (_q *SubscriptionResetCardGrantQuery) Where(ps ...predicate.SubscriptionResetCardGrant) *SubscriptionResetCardGrantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionResetCardGrantQuery) Limit(limit int) *SubscriptionResetCardGrantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionResetCardGrantQuery) Offset(offset int) *SubscriptionResetCardGrantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionResetCardGrantQuery) Unique(unique bool) *SubscriptionResetCardGrantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionResetCardGrantQuery) Order(o ...subscriptionresetcardgrant.OrderOption) *SubscriptionResetCardGrantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *SubscriptionResetCardGrantQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardgrant.UserTable, subscriptionresetcardgrant.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *SubscriptionResetCardGrantQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardgrant.GroupTable, subscriptionresetcardgrant.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIssuer chains the current query on the "issuer" edge.
func (_q *SubscriptionResetCardGrantQuery) QueryIssuer() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcardgrant.IssuerTable, subscriptionresetcardgrant.IssuerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsages chains the current query on the "usages" edge.
func (_q *SubscriptionResetCardGrantQuery) QueryUsages() *SubscriptionResetCardUsageQuery {
	query := (&SubscriptionResetCardUsageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.FieldID, selector),
			sqlgraph.To(subscriptionresetcardusage.Table, subscriptionresetcardusage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subscriptionresetcardgrant.UsagesTable, subscriptionresetcardgrant.UsagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionResetCardGrant entity from the query.
// Returns a *NotFoundError when no SubscriptionResetCardGrant was found.
func (_q *SubscriptionResetCardGrantQuery) First(ctx context.Context) (*SubscriptionResetCardGrant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionresetcardgrant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) FirstX(ctx context.Context) *SubscriptionResetCardGrant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionResetCardGrant ID from the query.
// Returns a *NotFoundError when no SubscriptionResetCardGrant ID was found.
func (_q *SubscriptionResetCardGrantQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionresetcardgrant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionResetCardGrant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionResetCardGrant entity is found.
// Returns a *NotFoundError when no SubscriptionResetCardGrant entities are found.
func (_q *SubscriptionResetCardGrantQuery) Only(ctx context.Context) (*SubscriptionResetCardGrant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionresetcardgrant.Label}
	default:
		return nil, &NotSingularError{subscriptionresetcardgrant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) OnlyX(ctx context.Context) *SubscriptionResetCardGrant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionResetCardGrant ID in the query.
// Returns a *NotSingularError when more than one SubscriptionResetCardGrant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionResetCardGrantQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionresetcardgrant.Label}
	default:
		err = &NotSingularError{subscriptionresetcardgrant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionResetCardGrants.
func (_q *SubscriptionResetCardGrantQuery) All(ctx context.Context) ([]*SubscriptionResetCardGrant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionResetCardGrant, *SubscriptionResetCardGrantQuery]()
	return withInterceptors[[]*SubscriptionResetCardGrant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) AllX(ctx context.Context) []*SubscriptionResetCardGrant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionResetCardGrant IDs.
func (_q *SubscriptionResetCardGrantQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionresetcardgrant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionResetCardGrantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionResetCardGrantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionResetCardGrantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionResetCardGrantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionResetCardGrantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionResetCardGrantQuery) Clone() *SubscriptionResetCardGrantQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionResetCardGrantQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]subscriptionresetcardgrant.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SubscriptionResetCardGrant{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		withGroup:  _q.withGroup.Clone(),
		withIssuer: _q.withIssuer.Clone(),
		withUsages: _q.withUsages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardGrantQuery) WithUser(opts ...func(*UserQuery)) *SubscriptionResetCardGrantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardGrantQuery) WithGroup(opts ...func(*GroupQuery)) *SubscriptionResetCardGrantQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithIssuer tells the query-builder to eager-load the nodes that are connected to
// the "issuer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardGrantQuery) WithIssuer(opts ...func(*UserQuery)) *SubscriptionResetCardGrantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIssuer = query
	return _q
}

// WithUsages tells the query-builder to eager-load the nodes that are connected to
// the "usages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardGrantQuery) WithUsages(opts ...func(*SubscriptionResetCardUsageQuery)) *SubscriptionResetCardGrantQuery {
	query := (&SubscriptionResetCardUsageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionResetCardGrant.Query().
//		GroupBy(subscriptionresetcardgrant.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardGrantQuery) GroupBy(field string, fields ...string) *SubscriptionResetCardGrantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionResetCardGrantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionresetcardgrant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SubscriptionResetCardGrant.Query().
//		Select(subscriptionresetcardgrant.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardGrantQuery) Select(fields ...string) *SubscriptionResetCardGrantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionResetCardGrantSelect{SubscriptionResetCardGrantQuery: _q}
	sbuild.label = subscriptionresetcardgrant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionResetCardGrantSelect configured with the given aggregations.
func (_q *SubscriptionResetCardGrantQuery) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardGrantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionResetCardGrantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionresetcardgrant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionResetCardGrantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionResetCardGrant, error) {
	var (
		nodes       = []*SubscriptionResetCardGrant{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withGroup != nil,
			_q.withIssuer != nil,
			_q.withUsages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionResetCardGrant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionResetCardGrant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardGrant, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardGrant, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIssuer; query != nil {
		if err := _q.loadIssuer(ctx, query, nodes, nil,
			func(n *SubscriptionResetCardGrant, e *User) { n.Edges.Issuer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsages; query != nil {
		if err := _q.loadUsages(ctx, query, nodes,
			func(n *SubscriptionResetCardGrant) { n.Edges.Usages = []*SubscriptionResetCardUsage{} },
			func(n *SubscriptionResetCardGrant, e *SubscriptionResetCardUsage) {
				n.Edges.Usages = append(n.Edges.Usages, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionResetCardGrantQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SubscriptionResetCardGrant, init func(*SubscriptionResetCardGrant), assign func(*SubscriptionResetCardGrant, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardGrant)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardGrantQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*SubscriptionResetCardGrant, init func(*SubscriptionResetCardGrant), assign func(*SubscriptionResetCardGrant, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardGrant)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardGrantQuery) loadIssuer(ctx context.Context, query *UserQuery, nodes []*SubscriptionResetCardGrant, init func(*SubscriptionResetCardGrant), assign func(*SubscriptionResetCardGrant, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCardGrant)
	for i := range nodes {
		if nodes[i].IssuedBy == nil {
			continue
		}
		fk := *nodes[i].IssuedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "issued_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardGrantQuery) loadUsages(ctx context.Context, query *SubscriptionResetCardUsageQuery, nodes []*SubscriptionResetCardGrant, init func(*SubscriptionResetCardGrant), assign func(*SubscriptionResetCardGrant, *SubscriptionResetCardUsage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubscriptionResetCardGrant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(subscriptionresetcardusage.FieldGrantID)
	}
	query.Where(predicate.SubscriptionResetCardUsage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subscriptionresetcardgrant.UsagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GrantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "grant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubscriptionResetCardGrantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionResetCardGrantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionresetcardgrant.Table, subscriptionresetcardgrant.Columns, sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcardgrant.FieldID)
		for i := range fields {
			if fields[i] != subscriptionresetcardgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardgrant.FieldUserID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardgrant.FieldGroupID)
		}
		if _q.withIssuer != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcardgrant.FieldIssuedBy)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionResetCardGrantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionresetcardgrant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionresetcardgrant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionResetCardGrantQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionResetCardGrantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionResetCardGrantQuery) ForShare(opts ...sql.LockOption) *SubscriptionResetCardGrantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionResetCardGrantGroupBy is the group-by builder for SubscriptionResetCardGrant entities.
type SubscriptionResetCardGrantGroupBy struct {
	selector
	build *SubscriptionResetCardGrantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionResetCardGrantGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardGrantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionResetCardGrantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardGrantQuery, *SubscriptionResetCardGrantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionResetCardGrantGroupBy) sqlScan(ctx context.Context, root *SubscriptionResetCardGrantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionResetCardGrantSelect is the builder for selecting fields of SubscriptionResetCardGrant entities.
type SubscriptionResetCardGrantSelect struct {
	*SubscriptionResetCardGrantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionResetCardGrantSelect) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardGrantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionResetCardGrantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardGrantQuery, *SubscriptionResetCardGrantSelect](ctx, _s.SubscriptionResetCardGrantQuery, _s, _s.inters, v)
}

func (_s *SubscriptionResetCardGrantSelect) sqlScan(ctx context.Context, root *SubscriptionResetCardGrantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
