// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
)

// SubscriptionResetCardGrantDelete is the builder for deleting a SubscriptionResetCardGrant entity.
type SubscriptionResetCardGrantDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionResetCardGrantMutation
}

// Where appends a list predicates to the SubscriptionResetCardGrantDelete builder.
func (_d *SubscriptionResetCardGrantDelete) Where(ps ...predicate.SubscriptionResetCardGrant) *SubscriptionResetCardGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionResetCardGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionResetCardGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionResetCardGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionresetcardgrant.Table, sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionResetCardGrantDeleteOne is the builder for deleting a single SubscriptionResetCardGrant entity.
type SubscriptionResetCardGrantDeleteOne struct {
	_d *SubscriptionResetCardGrantDelete
}

// Where appends a list predicates to the SubscriptionResetCardGrantDelete builder.
func (_d *SubscriptionResetCardGrantDeleteOne) Where(ps ...predicate.SubscriptionResetCardGrant) *SubscriptionResetCardGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionResetCardGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionresetcardgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionResetCardGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
