// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardgrant"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcardusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetCardGrantCreate is the builder for creating a SubscriptionResetCardGrant entity.
type SubscriptionResetCardGrantCreate struct {
	config
	mutation *SubscriptionResetCardGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionResetCardGrantCreate) SetCreatedAt(v time.Time) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionResetCardGrantCreate) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionResetCardGrantCreate) SetUserID(v int64) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionResetCardGrantCreate) SetGroupID(v int64) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetIssuedCount sets the "issued_count" field.
func (_c *SubscriptionResetCardGrantCreate) SetIssuedCount(v int) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetIssuedCount(v)
	return _c
}

// SetRemainingCount sets the "remaining_count" field.
func (_c *SubscriptionResetCardGrantCreate) SetRemainingCount(v int) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetRemainingCount(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionResetCardGrantCreate) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableExpiresAt(v *time.Time) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionResetCardGrantCreate) SetStatus(v string) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableStatus(v *string) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SubscriptionResetCardGrantCreate) SetSource(v string) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableSource(v *string) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *SubscriptionResetCardGrantCreate) SetRequestID(v string) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableRequestID(v *string) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetIssuedBy sets the "issued_by" field.
func (_c *SubscriptionResetCardGrantCreate) SetIssuedBy(v int64) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetIssuedBy(v)
	return _c
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableIssuedBy(v *int64) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetIssuedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubscriptionResetCardGrantCreate) SetNotes(v string) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableNotes(v *string) *SubscriptionResetCardGrantCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionResetCardGrantCreate) SetUser(v *User) *SubscriptionResetCardGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionResetCardGrantCreate) SetGroup(v *Group) *SubscriptionResetCardGrantCreate {
	return _c.SetGroupID(v.ID)
}

// SetIssuerID sets the "issuer" edge to the User entity by ID.
func (_c *SubscriptionResetCardGrantCreate) SetIssuerID(id int64) *SubscriptionResetCardGrantCreate {
	_c.mutation.SetIssuerID(id)
	return _c
}

// SetNillableIssuerID sets the "issuer" edge to the User entity by ID if the given value is not nil.
func (_c *SubscriptionResetCardGrantCreate) SetNillableIssuerID(id *int64) *SubscriptionResetCardGrantCreate {
	if id != nil {
		_c = _c.SetIssuerID(*id)
	}
	return _c
}

// SetIssuer sets the "issuer" edge to the User entity.
func (_c *SubscriptionResetCardGrantCreate) SetIssuer(v *User) *SubscriptionResetCardGrantCreate {
	return _c.SetIssuerID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the SubscriptionResetCardUsage entity by IDs.
func (_c *SubscriptionResetCardGrantCreate) AddUsageIDs(ids ...int64) *SubscriptionResetCardGrantCreate {
	_c.mutation.AddUsageIDs(ids...)
	return _c
}

// AddUsages adds the "usages" edges to the SubscriptionResetCardUsage entity.
func (_c *SubscriptionResetCardGrantCreate) AddUsages(v ...*SubscriptionResetCardUsage) *SubscriptionResetCardGrantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageIDs(ids...)
}

// Mutation returns the SubscriptionResetCardGrantMutation object of the builder.
func (_c *SubscriptionResetCardGrantCreate) Mutation() *SubscriptionResetCardGrantMutation {
	return _c.mutation
}

// Save creates the SubscriptionResetCardGrant in the database.
func (_c *SubscriptionResetCardGrantCreate) Save(ctx context.Context) (*SubscriptionResetCardGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionResetCardGrantCreate) SaveX(ctx context.Context) *SubscriptionResetCardGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetCardGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetCardGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionResetCardGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionresetcardgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionresetcardgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionresetcardgrant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := subscriptionresetcardgrant.DefaultSource
		_c.mutation.SetSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionResetCardGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.group_id"`)}
	}
	if _, ok := _c.mutation.IssuedCount(); !ok {
		return &ValidationError{Name: "issued_count", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.issued_count"`)}
	}
	if v, ok := _c.mutation.IssuedCount(); ok {
		if err := subscriptionresetcardgrant.IssuedCountValidator(v); err != nil {
			return &ValidationError{Name: "issued_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.issued_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RemainingCount(); !ok {
		return &ValidationError{Name: "remaining_count", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.remaining_count"`)}
	}
	if v, ok := _c.mutation.RemainingCount(); ok {
		if err := subscriptionresetcardgrant.RemainingCountValidator(v); err != nil {
			return &ValidationError{Name: "remaining_count", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.remaining_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionresetcardgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SubscriptionResetCardGrant.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := subscriptionresetcardgrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := subscriptionresetcardgrant.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCardGrant.request_id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionResetCardGrant.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionResetCardGrant.group"`)}
	}
	return nil
}

func (_c *SubscriptionResetCardGrantCreate) sqlSave(ctx context.Context) (*SubscriptionResetCardGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionResetCardGrantCreate) createSpec() (*SubscriptionResetCardGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionResetCardGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionresetcardgrant.Table, sqlgraph.NewFieldSpec(subscriptionresetcardgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IssuedCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldIssuedCount, field.TypeInt, value)
		_node.IssuedCount = value
	}
	if value, ok := _c.mutation.RemainingCount(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldRemainingCount, field.TypeInt, value)
		_node.RemainingCount = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(subscriptionresetcardgrant.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.UserTable,
			Columns: []string{subscriptionresetcardgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.GroupTable,
			Columns: []string{subscriptionresetcardgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcardgrant.IssuerTable,
			Columns: []string{subscriptionresetcardgrant.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IssuedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetcardgrant.UsagesTable,
			Columns: []string{subscriptionresetcardgrant.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcardusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetCardGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetCardGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetCardGrantCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetCardGrantUpsertOne {
	_c.conflict = opts
	return &SubscriptionResetCardGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetCardGrantCreate) OnConflictColumns(columns ...string) *SubscriptionResetCardGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetCardGrantUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionResetCardGrantUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionResetCardGrant node.
	SubscriptionResetCardGrantUpsertOne struct {
		create *SubscriptionResetCardGrantCreate
	}

	// SubscriptionResetCardGrantUpsert is the "OnConflict" setter.
	SubscriptionResetCardGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetCardGrantUpsert) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateUpdatedAt() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardGrantUpsert) SetUserID(v int64) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateUserID() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardGrantUpsert) SetGroupID(v int64) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateGroupID() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldGroupID)
	return u
}

// SetIssuedCount sets the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsert) SetIssuedCount(v int) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldIssuedCount, v)
	return u
}

// UpdateIssuedCount sets the "issued_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateIssuedCount() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldIssuedCount)
	return u
}

// AddIssuedCount adds v to the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsert) AddIssuedCount(v int) *SubscriptionResetCardGrantUpsert {
	u.Add(subscriptionresetcardgrant.FieldIssuedCount, v)
	return u
}

// SetRemainingCount sets the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsert) SetRemainingCount(v int) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldRemainingCount, v)
	return u
}

// UpdateRemainingCount sets the "remaining_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateRemainingCount() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldRemainingCount)
	return u
}

// AddRemainingCount adds v to the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsert) AddRemainingCount(v int) *SubscriptionResetCardGrantUpsert {
	u.Add(subscriptionresetcardgrant.FieldRemainingCount, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsert) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateExpiresAt() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsert) ClearExpiresAt() *SubscriptionResetCardGrantUpsert {
	u.SetNull(subscriptionresetcardgrant.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetCardGrantUpsert) SetStatus(v string) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateStatus() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldStatus)
	return u
}

// SetSource sets the "source" field.
func (u *SubscriptionResetCardGrantUpsert) SetSource(v string) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateSource() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldSource)
	return u
}

// SetIssuedBy sets the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsert) SetIssuedBy(v int64) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldIssuedBy, v)
	return u
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateIssuedBy() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldIssuedBy)
	return u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsert) ClearIssuedBy() *SubscriptionResetCardGrantUpsert {
	u.SetNull(subscriptionresetcardgrant.FieldIssuedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *SubscriptionResetCardGrantUpsert) SetNotes(v string) *SubscriptionResetCardGrantUpsert {
	u.Set(subscriptionresetcardgrant.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsert) UpdateNotes() *SubscriptionResetCardGrantUpsert {
	u.SetExcluded(subscriptionresetcardgrant.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionResetCardGrantUpsert) ClearNotes() *SubscriptionResetCardGrantUpsert {
	u.SetNull(subscriptionresetcardgrant.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetCardGrantUpsertOne) UpdateNewValues() *SubscriptionResetCardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionresetcardgrant.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(subscriptionresetcardgrant.FieldRequestID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionResetCardGrantUpsertOne) Ignore() *SubscriptionResetCardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetCardGrantUpsertOne) DoNothing() *SubscriptionResetCardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetCardGrantCreate.OnConflict
// documentation for more info.
func (u *SubscriptionResetCardGrantUpsertOne) Update(set func(*SubscriptionResetCardGrantUpsert)) *SubscriptionResetCardGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetCardGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateUpdatedAt() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetUserID(v int64) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateUserID() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetGroupID(v int64) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateGroupID() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetIssuedCount sets the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetIssuedCount(v int) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetIssuedCount(v)
	})
}

// AddIssuedCount adds v to the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsertOne) AddIssuedCount(v int) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.AddIssuedCount(v)
	})
}

// UpdateIssuedCount sets the "issued_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateIssuedCount() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateIssuedCount()
	})
}

// SetRemainingCount sets the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetRemainingCount(v int) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetRemainingCount(v)
	})
}

// AddRemainingCount adds v to the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsertOne) AddRemainingCount(v int) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.AddRemainingCount(v)
	})
}

// UpdateRemainingCount sets the "remaining_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateRemainingCount() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateRemainingCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateExpiresAt() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsertOne) ClearExpiresAt() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetStatus(v string) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateStatus() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetSource(v string) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateSource() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateSource()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetIssuedBy(v int64) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateIssuedBy() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsertOne) ClearIssuedBy() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearIssuedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionResetCardGrantUpsertOne) SetNotes(v string) *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertOne) UpdateNotes() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionResetCardGrantUpsertOne) ClearNotes() *SubscriptionResetCardGrantUpsertOne {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionResetCardGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetCardGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetCardGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionResetCardGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionResetCardGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionResetCardGrantCreateBulk is the builder for creating many SubscriptionResetCardGrant entities in bulk.
type SubscriptionResetCardGrantCreateBulk struct {
	config
	err      error
	builders []*SubscriptionResetCardGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionResetCardGrant entities in the database.
func (_c *SubscriptionResetCardGrantCreateBulk) Save(ctx context.Context) ([]*SubscriptionResetCardGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionResetCardGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionResetCardGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionResetCardGrantCreateBulk) SaveX(ctx context.Context) []*SubscriptionResetCardGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetCardGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetCardGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetCardGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetCardGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetCardGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetCardGrantUpsertBulk {
	_c.conflict = opts
	return &SubscriptionResetCardGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetCardGrantCreateBulk) OnConflictColumns(columns ...string) *SubscriptionResetCardGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetCardGrantUpsertBulk{
		create: _c,
	}
}

// SubscriptionResetCardGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionResetCardGrant nodes.
type SubscriptionResetCardGrantUpsertBulk struct {
	create *SubscriptionResetCardGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateNewValues() *SubscriptionResetCardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionresetcardgrant.FieldCreatedAt)
			}
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(subscriptionresetcardgrant.FieldRequestID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetCardGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionResetCardGrantUpsertBulk) Ignore() *SubscriptionResetCardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetCardGrantUpsertBulk) DoNothing() *SubscriptionResetCardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetCardGrantCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionResetCardGrantUpsertBulk) Update(set func(*SubscriptionResetCardGrantUpsert)) *SubscriptionResetCardGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetCardGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateUpdatedAt() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetUserID(v int64) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateUserID() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetGroupID(v int64) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateGroupID() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetIssuedCount sets the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetIssuedCount(v int) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetIssuedCount(v)
	})
}

// AddIssuedCount adds v to the "issued_count" field.
func (u *SubscriptionResetCardGrantUpsertBulk) AddIssuedCount(v int) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.AddIssuedCount(v)
	})
}

// UpdateIssuedCount sets the "issued_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateIssuedCount() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateIssuedCount()
	})
}

// SetRemainingCount sets the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetRemainingCount(v int) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetRemainingCount(v)
	})
}

// AddRemainingCount adds v to the "remaining_count" field.
func (u *SubscriptionResetCardGrantUpsertBulk) AddRemainingCount(v int) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.AddRemainingCount(v)
	})
}

// UpdateRemainingCount sets the "remaining_count" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateRemainingCount() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateRemainingCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateExpiresAt() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionResetCardGrantUpsertBulk) ClearExpiresAt() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetStatus(v string) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateStatus() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetSource(v string) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateSource() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateSource()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetIssuedBy(v int64) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateIssuedBy() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *SubscriptionResetCardGrantUpsertBulk) ClearIssuedBy() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearIssuedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionResetCardGrantUpsertBulk) SetNotes(v string) *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionResetCardGrantUpsertBulk) UpdateNotes() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionResetCardGrantUpsertBulk) ClearNotes() *SubscriptionResetCardGrantUpsertBulk {
	return u.Update(func(s *SubscriptionResetCardGrantUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionResetCardGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionResetCardGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetCardGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetCardGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
