// Code generated by ent, DO NOT EDIT.

package subscriptionresetcardgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionresetcardgrant type in the database.
	Label = "subscription_reset_card_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldIssuedCount holds the string denoting the issued_count field in the database.
	FieldIssuedCount = "issued_count"
	// FieldRemainingCount holds the string denoting the remaining_count field in the database.
	FieldRemainingCount = "remaining_count"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldIssuedBy holds the string denoting the issued_by field in the database.
	FieldIssuedBy = "issued_by"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeIssuer holds the string denoting the issuer edge name in mutations.
	EdgeIssuer = "issuer"
	// EdgeUsages holds the string denoting the usages edge name in mutations.
	EdgeUsages = "usages"
	// Table holds the table name of the subscriptionresetcardgrant in the database.
	Table = "subscription_reset_card_grants"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "subscription_reset_card_grants"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "subscription_reset_card_grants"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// IssuerTable is the table that holds the issuer relation/edge.
	IssuerTable = "subscription_reset_card_grants"
	// IssuerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	IssuerInverseTable = "users"
	// IssuerColumn is the table column denoting the issuer relation/edge.
	IssuerColumn = "issued_by"
	// UsagesTable is the table that holds the usages relation/edge.
	UsagesTable = "subscription_reset_card_usages"
	// UsagesInverseTable is the table name for the SubscriptionResetCardUsage entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionresetcardusage" package.
	UsagesInverseTable = "subscription_reset_card_usages"
	// UsagesColumn is the table column denoting the usages relation/edge.
	UsagesColumn = "grant_id"
)

// Columns holds all SQL columns for subscriptionresetcardgrant fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldGroupID,
	FieldIssuedCount,
	FieldRemainingCount,
	FieldExpiresAt,
	FieldStatus,
	FieldSource,
	FieldRequestID,
	FieldIssuedBy,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IssuedCountValidator is a validator for the "issued_count" field. It is called by the builders before save.
	IssuedCountValidator func(int) error
	// RemainingCountValidator is a validator for the "remaining_count" field. It is called by the builders before save.
	RemainingCountValidator func(int) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
)

// OrderOption defines the ordering options for the SubscriptionResetCardGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByIssuedCount orders the results by the issued_count field.
func ByIssuedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedCount, opts...).ToFunc()
}

// ByRemainingCount orders the results by the remaining_count field.
func ByRemainingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainingCount, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByIssuedBy orders the results by the issued_by field.
func ByIssuedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedBy, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByIssuerField orders the results by issuer field.
func ByIssuerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIssuerStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsagesCount orders the results by usages count.
func ByUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagesStep(), opts...)
	}
}

// ByUsages orders the results by usages terms.
func ByUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newIssuerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IssuerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
	)
}
func newUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
	)
}
