// Code generated by ent, DO NOT EDIT.

package subscriptionresetcardgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldGroupID, v))
}

// IssuedCount applies equality check predicate on the "issued_count" field. It's identical to IssuedCountEQ.
func IssuedCount(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldIssuedCount, v))
}

// RemainingCount applies equality check predicate on the "remaining_count" field. It's identical to RemainingCountEQ.
func RemainingCount(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldRemainingCount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldSource, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldRequestID, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldIssuedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldGroupID, vs...))
}

// IssuedCountEQ applies the EQ predicate on the "issued_count" field.
func IssuedCountEQ(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldIssuedCount, v))
}

// IssuedCountNEQ applies the NEQ predicate on the "issued_count" field.
func IssuedCountNEQ(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldIssuedCount, v))
}

// IssuedCountIn applies the In predicate on the "issued_count" field.
func IssuedCountIn(vs ...int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldIssuedCount, vs...))
}

// IssuedCountNotIn applies the NotIn predicate on the "issued_count" field.
func IssuedCountNotIn(vs ...int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldIssuedCount, vs...))
}

// IssuedCountGT applies the GT predicate on the "issued_count" field.
func IssuedCountGT(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldIssuedCount, v))
}

// IssuedCountGTE applies the GTE predicate on the "issued_count" field.
func IssuedCountGTE(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldIssuedCount, v))
}

// IssuedCountLT applies the LT predicate on the "issued_count" field.
func IssuedCountLT(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldIssuedCount, v))
}

// IssuedCountLTE applies the LTE predicate on the "issued_count" field.
func IssuedCountLTE(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldIssuedCount, v))
}

// RemainingCountEQ applies the EQ predicate on the "remaining_count" field.
func RemainingCountEQ(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldRemainingCount, v))
}

// RemainingCountNEQ applies the NEQ predicate on the "remaining_count" field.
func RemainingCountNEQ(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldRemainingCount, v))
}

// RemainingCountIn applies the In predicate on the "remaining_count" field.
func RemainingCountIn(vs ...int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldRemainingCount, vs...))
}

// RemainingCountNotIn applies the NotIn predicate on the "remaining_count" field.
func RemainingCountNotIn(vs ...int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldRemainingCount, vs...))
}

// RemainingCountGT applies the GT predicate on the "remaining_count" field.
func RemainingCountGT(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldRemainingCount, v))
}

// RemainingCountGTE applies the GTE predicate on the "remaining_count" field.
func RemainingCountGTE(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldRemainingCount, v))
}

// RemainingCountLT applies the LT predicate on the "remaining_count" field.
func RemainingCountLT(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldRemainingCount, v))
}

// RemainingCountLTE applies the LTE predicate on the "remaining_count" field.
func RemainingCountLTE(v int) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldRemainingCount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotNull(FieldExpiresAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContainsFold(FieldStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContainsFold(FieldSource, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContainsFold(FieldRequestID, v))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...int64) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByIsNil applies the IsNil predicate on the "issued_by" field.
func IssuedByIsNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIsNull(FieldIssuedBy))
}

// IssuedByNotNil applies the NotNil predicate on the "issued_by" field.
func IssuedByNotNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotNull(FieldIssuedBy))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.FieldContainsFold(FieldNotes, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIssuer applies the HasEdge predicate on the "issuer" edge.
func HasIssuer() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuerWith applies the HasEdge predicate on the "issuer" edge with a given conditions (other predicates).
func HasIssuerWith(preds ...predicate.User) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := newIssuerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsages applies the HasEdge predicate on the "usages" edge.
func HasUsages() predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsagesWith applies the HasEdge predicate on the "usages" edge with a given conditions (other predicates).
func HasUsagesWith(preds ...predicate.SubscriptionResetCardUsage) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(func(s *sql.Selector) {
		step := newUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionResetCardGrant) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionResetCardGrant) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionResetCardGrant) predicate.SubscriptionResetCardGrant {
	return predicate.SubscriptionResetCardGrant(sql.NotPredicates(p))
}
